import { useState } from 'react';
import { ChevronDown, Database, Grid3x3 as Grid3X3, Menu, MoveHorizontal as MoreHorizontal, Info, PanelLeftClose, PanelLeftOpen, Table2 } from 'lucide-react';
import { ColumnDetailsDrawer } from '@/components/ColumnDetailsDrawer';
import { TableSummaryDrawer } from '@/components/TableSummaryDrawer';

const schemaTables = { public: { branch: 5, customer: 12, employee: 9 }, lending: { loan_account: 18, loan_application: 14, product: 9, repayment: 11 }, analytics: { portfolio_summary: 8, branch_performance: 10, product_metrics: 7 }, risk: { risk_rating: 6, npa_account: 13, credit_score: 5 }, collections: { collection_bucket: 8, collection_payment: 10, collection_target: 6 }, reference: { dim_region: 6, dim_product: 8, dim_date: 7 }, staging: { loan_account_stg: 18, customer_stg: 12 }, reporting: { monthly_branch_report: 14, portfolio_report: 10 } } as const;
const columns = [
  ['branch_code', 'VARCHAR(20)', 'Yes', 'No', 'branch (branch_code)', '3 Roles', 'Active'],
  ['branch_name', 'VARCHAR(100)', 'No', 'No', '—', '3 Roles', 'Active'],
  ['branch_type', 'VARCHAR(50)', 'No', 'No', '—', '2 Roles', 'Active'],
  ['region_code', 'VARCHAR(20)', 'Yes', 'No', 'region (region_code)', '2 Roles', 'Active'],
  ['branch_status', 'VARCHAR(20)', 'No', 'No', '—', '3 Roles', 'Active'],
  ['manager_id', 'NUMBER', 'Yes', 'No', '—', '2 Roles', 'Active'],
  ['manager_name', 'VARCHAR(100)', 'Yes', 'No', '—', '2 Roles', 'Active'],
  ['address_line1', 'VARCHAR(150)', 'Yes', 'No', '—', '3 Roles', 'Active'],
  ['address_line2', 'VARCHAR(150)', 'Yes', 'No', '—', '3 Roles', 'Active'],
  ['city', 'VARCHAR(80)', 'Yes', 'No', '—', '3 Roles', 'Active'],
  ['state', 'VARCHAR(80)', 'Yes', 'No', '—', '3 Roles', 'Active'],
  ['postal_code', 'VARCHAR(20)', 'Yes', 'No', '—', '3 Roles', 'Active'],
  ['phone_number', 'VARCHAR(25)', 'Yes', 'Yes', '—', '2 Roles', 'Active'],
  ['email', 'VARCHAR(150)', 'Yes', 'Yes', '—', '2 Roles', 'Active'],
  ['opened_date', 'DATE', 'No', 'No', '—', '3 Roles', 'Active'],
  ['closed_date', 'DATE', 'Yes', 'No', '—', '3 Roles', 'Inactive'],
  ['business_segment', 'VARCHAR(50)', 'Yes', 'No', '—', '3 Roles', 'Active'],
  ['employee_count', 'NUMBER', 'No', 'No', '—', '3 Roles', 'Active'],
  ['loan_count', 'NUMBER', 'No', 'No', '—', '3 Roles', 'Active'],
  ['deposit_count', 'DECIMAL(18,2)', 'No', 'No', '—', '3 Roles', 'Active'],
  ['branch_target', 'DECIMAL(18,2)', 'Yes', 'No', '—', '2 Roles', 'Active'],
  ['created_date', 'DATE', 'No', 'No', '—', '1 Role', 'Active'],
  ['updated_date', 'DATE', 'No', 'No', '—', '1 Role', 'Active'],
  ['is_active', 'BOOLEAN', 'No', 'No', '—', '3 Roles', 'Active'],
];

export function AdminTablesPage({ onBack, onAudit, shellManaged = false }: { onBack: () => void; onAudit: () => void; shellManaged?: boolean }) {
  const [sidebarOpen, setSidebarOpen] = useState(true);
  const [selectedColumn, setSelectedColumn] = useState<string | null>(null);
  const [showTableSummary, setShowTableSummary] = useState(false);
  const [selectedTable, setSelectedTable] = useState('branch');
  const [expandedSchemas, setExpandedSchemas] = useState<Record<string, boolean>>({ public: true });
  const [expandedTables, setExpandedTables] = useState<Record<string, boolean>>({ public: true });
  const [paneState, setPaneState] = useState({ left: true, center: true });
  const [leftWidth, setLeftWidth] = useState(245);
  const resizePane = (side: 'left' | 'right', event: React.PointerEvent<HTMLDivElement>) => {
    event.currentTarget.setPointerCapture(event.pointerId);
    const move = (moveEvent: PointerEvent) => setLeftWidth(Math.min(360, Math.max(190, moveEvent.clientX)));
    const stop = () => { window.removeEventListener('pointermove', move); window.removeEventListener('pointerup', stop); };
    window.addEventListener('pointermove', move); window.addEventListener('pointerup', stop);
  };
  return <><div className="flex min-h-0 flex-1 flex-col bg-white text-navy-900">
    <div className={`grid min-h-0 flex-1 ${shellManaged ? 'grid-cols-1' : sidebarOpen ? 'grid-cols-[245px_minmax(0,1fr)]' : 'grid-cols-[56px_minmax(0,1fr)]'} transition-[grid-template-columns] duration-200`}>
      <aside className={`flex flex-col border-r border-surface-200 px-2 py-4 ${shellManaged ? 'hidden' : ''}`}><button type="button" onClick={() => setSidebarOpen((open) => !open)} aria-label={sidebarOpen ? 'Collapse navigation' : 'Expand navigation'} className="mb-5 flex size-9 items-center justify-center rounded-lg text-blue-900 hover:bg-blue-50"><Menu className="size-4" /></button>{sidebarOpen && <><AdminNav onAudit={onAudit} /><p className="mt-auto px-2 text-[10px] text-ink-500">© 2026 ReportIQ. All rights reserved.</p></>}</aside>
      <main className="flex min-h-0 min-w-0 flex-1 flex-col overflow-hidden px-8 py-7"><div className="mb-6 shrink-0"><h1 className="font-display text-[24px] font-bold tracking-[-0.03em]">Tables &amp; Columns</h1><p className="mt-1 text-[12px] text-ink-500">Browse your data assets and manage metadata, parameters, PII and access.</p></div>
        <div className="flex min-h-0 flex-1 divide-x divide-surface-200"><div style={{ width: paneState.left ? leftWidth : 48 }} className="relative flex min-h-0 shrink-0 flex-col transition-[width] duration-200"><PaneToggle label="Schemas / Tables" open={paneState.left} onClick={() => setPaneState((state) => ({ ...state, left: !state.left }))} /><div className={paneState.left ? 'min-h-0 flex-1 overflow-y-auto' : 'hidden'}><SchemaTree onSelectTable={setSelectedTable} /></div></div><div role="separator" aria-label="Resize schemas pane" onPointerDown={(event) => resizePane('left', event)} className="w-1 shrink-0 cursor-col-resize hover:bg-blue-100" /><section className={`${paneState.center ? 'flex min-w-0 flex-1 flex-col' : 'w-12 shrink-0'} min-h-0 overflow-hidden px-5 py-5 transition-[width] duration-200`}><div className="shrink-0"><div className="flex items-center gap-3"><Table2 className="size-7 text-blue-600" /><div><h2 className="font-display text-[18px] font-bold">public.{selectedTable} <span className="rounded-md bg-blue-50 px-2 py-1 text-[10px] text-blue-600">Table</span></h2></div><div className="flex items-center gap-2"><button type="button" onClick={() => setShowTableSummary(true)} aria-label="Open table summary" className="flex size-8 items-center justify-center rounded-md border border-surface-200 text-blue-600 hover:bg-blue-50"><Info className="size-4" /></button><button type="button" aria-label="More table actions" className="flex size-8 items-center justify-center text-navy-900"><MoreHorizontal className="size-5" /></button></div></div></div><div className="mt-4 min-h-0 flex-1 overflow-y-auto"><div className="overflow-x-auto"><table className="w-full text-left text-[11px]"><thead><tr className="sticky top-0 z-10 border-y border-surface-200 bg-white text-[10px] text-ink-500">{['Column Name','Data Type','Parameterizable','PII','Value Mapping','Access','Status',''].map((heading) => <th key={heading} className="px-2 py-3 font-semibold">{heading}</th>)}</tr></thead><tbody>{columns.map((column) => <tr key={column[0]} onClick={() => setSelectedColumn(column[0])} className="cursor-pointer border-b border-surface-200 hover:bg-blue-50/40"><td className="px-2 py-4 font-semibold">{column[0]}</td><td className="px-2">{column[1]}</td><td className="px-2"><Badge value={column[2]} good={column[2] === 'Yes'} /></td><td className="px-2"><Badge value={column[3]} good={false} /></td><td className="px-2 text-blue-600">{column[4]}</td><td className="px-2 text-blue-600">{column[5]}</td><td className="px-2"><Badge value={column[6]} good /></td><td className="px-2"><button type="button" onClick={(event) => { event.stopPropagation(); setSelectedColumn(column[0]); }} aria-label={`Open details for ${column[0]}`}><MoreHorizontal className="size-4" /></button></td></tr>)}</tbody></table><p className="mt-5 text-[11px] text-ink-500">Showing 1 to {columns.length} of 5 columns</p></div></div></section></div>
      </main></div></div>{selectedColumn && <ColumnDetailsDrawer column={selectedColumn} onClose={() => setSelectedColumn(null)} />}{showTableSummary && <TableSummaryDrawer onClose={() => setShowTableSummary(false)} onEdit={() => setShowTableSummary(false)} onViewAccess={() => setShowTableSummary(false)} />}</>;
}

function PaneToggle({ label, open, onClick }: { label: string; open: boolean; onClick: () => void }) { const Icon = open ? PanelLeftClose : PanelLeftOpen; return <button type="button" onClick={onClick} aria-label={`${open ? 'Collapse' : 'Expand'} ${label}`} title={`${open ? 'Collapse' : 'Expand'} ${label}`} className="mb-3 flex size-8 items-center justify-center rounded-md border border-surface-200 text-blue-900 hover:bg-blue-50"><Icon className="size-4" /></button>; }
function AdminNav({ onAudit }: { onAudit: () => void }) { return <nav className="flex flex-col gap-7 text-[13px] font-semibold"><NavGroup title="DATA GOVERNANCE" items={['Tables & Columns']} active /><button type="button" onClick={onAudit} className="rounded-lg px-3 py-3 text-left text-blue-900 hover:bg-blue-50">Audit Trail</button><NavGroup title="AI OBSERVABILITY" items={['AI Traceability']} /><NavGroup title="COMPLIANCE" items={['Policy Packs']} /></nav>; }
function NavGroup({ title, items, active = false }: { title: string; items: string[]; active?: boolean }) { return <div><p className="mb-3 px-2 text-[11px] font-bold text-blue-900">{title}</p>{items.map((item, index) => <div key={item} className={`flex items-center gap-3 rounded-lg px-3 py-3 ${active && index === 0 ? 'bg-blue-50 text-blue-600' : 'text-blue-900'}`}><Grid3X3 className="size-4" />{item}</div>)}</div>; }
function Badge({ value, good }: { value: string; good: boolean }) { return <span className={`rounded-md px-2 py-1 text-[10px] font-bold ${good ? 'bg-mint-100 text-mint-700' : 'bg-surface-100 text-navy-900'}`}>{value}</span>; }
function SchemaTree({ onSelectTable }: { onSelectTable: (table: string) => void }) { const [expandedSchemas, setExpandedSchemas] = useState<Record<string, boolean>>({ public: true }); const [expandedTables, setExpandedTables] = useState<Record<string, boolean>>({ public: true }); const [selectedSchema, setSelectedSchema] = useState('public'); const [selectedTable, setSelectedTable] = useState('branch'); return <aside className="border-r border-surface-200 px-5 py-5"><h3 className="text-[13px] font-bold">Schemas</h3><div className="mt-5 flex flex-col gap-2 text-[11px] font-semibold">{Object.entries(schemaTables).map(([schema, tables]) => { const isOpen = expandedSchemas[schema]; const tableOpen = expandedTables[schema]; return <div key={schema}><button type="button" onClick={() => { setSelectedSchema(schema); setExpandedSchemas((state) => ({ ...state, [schema]: !isOpen })); }} className={`flex w-full items-center gap-2 rounded-md px-2 py-2 text-left ${selectedSchema === schema ? 'text-blue-600' : 'text-blue-900'}`}><ChevronDown className={`size-3 transition-transform ${isOpen ? '' : '-rotate-90'}`} /><Database className="size-4" />{schema}<span className="ml-auto rounded-full bg-surface-100 px-2 py-1">{Object.keys(tables).length}</span></button>{isOpen && <div className="ml-5 flex flex-col gap-2"><button type="button" onClick={() => setExpandedTables((state) => ({ ...state, [schema]: !tableOpen }))} className="flex items-center gap-2 px-2 py-2 text-left text-blue-900"><ChevronDown className={`size-3 transition-transform ${tableOpen ? '' : '-rotate-90'}`} />Tables</button>{tableOpen && Object.entries(tables).map(([table, count]) => <button type="button" key={table} onClick={() => { setSelectedTable(table); onSelectTable(table); setSelectedSchema(schema); }} className={`flex items-center gap-2 rounded-md px-2 py-2 text-left ${selectedTable === table ? 'bg-blue-50 text-blue-600' : 'text-blue-900'}`}><Table2 className="size-3.5" />{table}<span className="ml-auto rounded-full bg-surface-100 px-1.5 py-0.5 text-[9px]">{count}</span></button>)}</div>}</div>; })}</div></aside>; }