'use client';

import { useState } from 'react';
import { X, ChevronDown, CheckCircle2 } from 'lucide-react';

type Props = { column: string; onClose: () => void };

export function ColumnDetailsDrawer({ column, onClose }: Props) {
  const [tab, setTab] = useState<'Properties' | 'Access'>('Properties');
  const [parameterable, setParameterable] = useState(column === 'branch_code');
  const [pii, setPii] = useState(false);
  const [active, setActive] = useState(true);
  const [roles, setRoles] = useState(['Data Analyst', 'Branch Manager', 'Reporting User']);
  const [saved, setSaved] = useState(false);
  const toggleRole = (role: string) => setRoles((current) => current.includes(role) ? current.filter((item) => item !== role) : [...current, role]);
  return <aside className="fixed inset-y-0 right-0 z-40 flex w-full max-w-[430px] flex-col border-l border-surface-200 bg-white shadow-[-8px_0_30px_rgba(15,35,55,0.08)]">
    <header className="flex items-start justify-between border-b border-surface-200 px-6 py-5"><div><h2 className="font-display text-[18px] font-bold text-navy-900">Column Details</h2><p className="mt-4 text-[10px] font-bold uppercase tracking-wide text-ink-400">Column</p><p className="mt-2 text-[16px] font-bold text-navy-900">{column}</p><p className="mt-1 text-[11px] text-ink-500">public.branch</p></div><button type="button" onClick={onClose} aria-label="Close column details"><X className="size-5 text-ink-500" /></button></header>
    <div className="flex border-b border-surface-200 px-6"><button type="button" onClick={() => setTab('Properties')} className={`border-b-2 px-4 py-3 text-[12px] font-bold ${tab === 'Properties' ? 'border-blue-600 text-blue-600' : 'border-transparent text-ink-500'}`}>Properties</button><button type="button" onClick={() => setTab('Access')} className={`border-b-2 px-4 py-3 text-[12px] font-bold ${tab === 'Access' ? 'border-blue-600 text-blue-600' : 'border-transparent text-ink-500'}`}>Access</button></div>
    <div className="flex-1 overflow-y-auto p-5">{tab === 'Properties' ? <div className="flex flex-col gap-3"><section className="rounded-lg border border-surface-200 p-4"><h3 className="text-[13px] font-bold">Parameter Configuration</h3><Toggle label="Mark as Parameterable" checked={parameterable} onChange={() => setParameterable(!parameterable)} />{parameterable && <div className="mt-3 rounded-lg bg-surface-50 p-3"><h4 className="text-[12px] font-bold">Display Value Mapping</h4><div className="mt-3 grid grid-cols-2 gap-3"><Select label="Lookup Table" value="branch" /><Select label="Lookup Key Column" value={column} /><Select label="Display Value Column" value="branch_name" /></div><p className="mt-3 flex items-center gap-1 text-[10px] font-semibold text-mint-700"><CheckCircle2 className="size-3.5" /> Mapping valid</p></div>}</section><section className="rounded-lg border border-surface-200 p-4"><h3 className="text-[13px] font-bold">PII Classification</h3><Toggle label="Mark as PII" checked={pii} onChange={() => setPii(!pii)} />{pii && <div className="mt-3 grid grid-cols-2 gap-3"><Select label="PII Category" value="Business Identifier" /><Select label="Sensitivity Level" value="Internal" /><label className="col-span-2 text-[10px] font-semibold">Description<textarea className="mt-1 h-16 w-full rounded-md border border-surface-200 p-2 text-[11px] outline-none" placeholder="Optional description" /></label></div>}</section><section className="rounded-lg border border-surface-200 p-4"><h3 className="text-[13px] font-bold">Column Properties</h3><div className="mt-4 grid grid-cols-2 gap-4 text-[10px]"><Meta label="Data Type" value={column === 'created_date' ? 'DATE' : 'VARCHAR(20)'} /><Meta label="Nullable" value="No" /><Meta label="Default Value" value="—" /><Meta label="Description" value="Branch unique code" /></div></section><section className="rounded-lg border border-surface-200 p-4"><h3 className="text-[13px] font-bold">Status</h3><Toggle label="Active" checked={active} onChange={() => setActive(!active)} /></section></div> : <section className="rounded-lg border border-surface-200 p-4"><h3 className="text-[13px] font-bold">Assigned roles</h3><div className="mt-4 flex flex-col gap-2">{['Data Analyst', 'Branch Manager', 'Reporting User'].map((role) => <button type="button" key={role} onClick={() => toggleRole(role)} className={`flex items-center justify-between rounded-md border px-3 py-2 text-left text-[11px] ${roles.includes(role) ? 'border-blue-200 bg-blue-50 text-blue-700' : 'border-surface-200 text-ink-500'}`}>{role}<span>{roles.includes(role) ? 'Assigned' : 'Add'}</span></button>)}</div><button type="button" className="mt-4 text-[11px] font-bold text-blue-600">View assigned roles</button></section>}</div>
    <footer className="flex items-center justify-end gap-3 border-t border-surface-200 px-5 py-4"><button type="button" onClick={onClose} className="rounded-md border border-surface-200 px-4 py-2 text-[11px] font-bold text-navy-900">Cancel</button><button type="button" onClick={() => setSaved(true)} className="rounded-md bg-blue-600 px-4 py-2 text-[11px] font-bold text-white">{saved ? 'Saved' : 'Save Changes'}</button></footer>
  </aside>;
}
function Toggle({ label, checked, onChange }: { label: string; checked: boolean; onChange: () => void }) { return <div className="mt-4 flex items-center justify-between text-[11px] font-semibold"><span>{label}</span><button type="button" aria-label={label} aria-pressed={checked} onClick={onChange} className={`relative h-5 w-9 shrink-0 rounded-full ${checked ? 'bg-blue-600' : 'bg-surface-300'}`}><span className={`absolute top-0.5 size-4 rounded-full bg-white transition ${checked ? 'left-[18px]' : 'left-0.5'}`} /></button></div>; }
function Select({ label, value }: { label: string; value: string }) { return <label className="text-[10px] font-semibold">{label}<span className="mt-1 flex items-center justify-between rounded-md border border-surface-200 bg-white px-2 py-2 text-[11px] font-normal"><span>{value}</span><ChevronDown className="size-3" /></span></label>; }
function Meta({ label, value }: { label: string; value: string }) { return <div><p className="text-ink-500">{label}</p><p className="mt-1 font-semibold text-navy-900">{value}</p></div>; }
