import { useState, type ReactNode } from 'react';
import { ChartBar as BarChart3, ChartLine as LineChart, Clock3, FileText, LockKeyhole, MessageSquareText, Pin, Plus, Search, Send, Sparkles, Star, UsersRound } from 'lucide-react';
import { myWidgets, pinnedReports, recentSessions, recommendedWidgets, type Widget, type WidgetKind } from '@/data/homeData';

type HomePageProps = { onNewSession: () => void; onOpenReports: () => void; isNewUser?: boolean; userName?: string };

export function HomePage({ onNewSession, onOpenReports, isNewUser = false, userName = 'Rahul' }: HomePageProps) {
  const [addedWidgets, setAddedWidgets] = useState<string[]>([]);
  const [question, setQuestion] = useState('');

  function addWidget(id: string) {
    setAddedWidgets((current) => current.includes(id) ? current : [...current, id]);
  }

  return (
    <main className="min-h-0 flex-1 overflow-y-auto bg-white">
      <div className="mx-auto max-w-[1480px] px-5 py-6 sm:px-8 lg:px-10">
        <div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-center">
          <div>
            <h1 className="font-display text-[24px] font-bold tracking-[-0.04em] text-navy-900 sm:text-[27px]">{isNewUser ? `Welcome to ReportIQ, ${userName}!` : `Good morning, ${userName}!`}</h1>
            <p className="mt-1.5 text-[13px] text-ink-500">{isNewUser ? "Let's get you started by adding widgets and building your home dashboard." : "Here's what's happening with your business today."}</p>
          </div>
          <div className="flex gap-2">
            <button type="button" className="inline-flex items-center gap-2 rounded-lg border border-surface-200 bg-white px-4 py-2.5 text-[12px] font-bold text-navy-900 transition hover:border-mint-300 hover:bg-mint-50"><Plus className="h-4 w-4" /> Add widget</button>
            <button type="button" onClick={onNewSession} className="inline-flex items-center gap-2 rounded-lg bg-navy-900 px-4 py-2.5 text-[12px] font-bold text-white transition hover:bg-navy-800"><Plus className="h-4 w-4" /> New session</button>
          </div>
        </div>

        <div className="mt-7 grid gap-5 lg:grid-cols-[275px_minmax(0,1fr)]">
          <aside className="flex flex-col gap-4">
            <SideCard title="Pinned reports" icon={<Pin className="h-4 w-4" />} onViewAll={onOpenReports}>
              {isNewUser ? <EmptySideState icon={<FileText className="h-9 w-9" />} title="No pinned reports yet" text="Pin your frequently used reports for quick access." action="Explore reports" onAction={onOpenReports} /> : <div className="divide-y divide-surface-100">{pinnedReports.map((report) => <button type="button" key={report.name} className="flex w-full items-center gap-2.5 py-2.5 text-left transition hover:bg-mint-50/50"><span className="flex h-7 w-7 shrink-0 items-center justify-center rounded-md bg-mint-50 text-mint-700"><FileText className="h-4 w-4" /></span><span className="min-w-0 flex-1"><span className="block truncate text-[11px] font-bold text-navy-900">{report.name}</span><span className="mt-0.5 block text-[10px] text-ink-500">{report.updated}</span></span><Star className={`h-3.5 w-3.5 shrink-0 ${report.pinned ? 'fill-amber-400 text-amber-400' : 'text-ink-300'}`} /></button>)}</div>}
            </SideCard>

            <SideCard title="Recent sessions" icon={<Clock3 className="h-4 w-4" />} onViewAll={onNewSession}>
              {isNewUser ? <EmptySideState icon={<LineChart className="h-9 w-9" />} title="No recent sessions" text="Your recent sessions will appear here once you start exploring." action="Start a new session" onAction={onNewSession} /> : <div className="divide-y divide-surface-100">{recentSessions.map((session) => <button type="button" key={session.name} onClick={onNewSession} className="flex w-full items-center gap-2 py-2.5 text-left transition hover:bg-mint-50/50"><span className="min-w-0 flex-1"><span className="block truncate text-[11px] font-bold text-navy-900">{session.name}</span><span className="mt-0.5 block text-[10px] text-ink-500">{session.time}</span></span><span className={`rounded-md px-2 py-1 text-[9px] font-bold ${session.kind === 'TABLE' ? 'bg-mint-100 text-mint-700' : 'bg-[#eeebff] text-[#5e55ce]'}`}>{session.kind === 'TABLE' ? 'Table' : 'Chart'}</span></button>)}</div>}
            </SideCard>

            <section className="rounded-xl border border-surface-200 bg-white p-4 shadow-[0_2px_8px_rgba(14,42,59,0.03)]"><div className="flex items-center gap-2"><MessageSquareText className="h-4 w-4 text-mint-600" /><h2 className="font-display text-[12px] font-bold text-navy-900">Ask anything, get instant insights</h2></div><p className="mt-2 text-[11px] leading-5 text-ink-500">Ask in natural language and get answers with charts, tables, or reports.</p><label className="mt-3 flex items-center gap-2 rounded-lg bg-mint-50 px-3 py-2 text-ink-300"><Search className="h-3.5 w-3.5 shrink-0" /><span className="sr-only">Ask a question</span><input value={question} onChange={(event) => setQuestion(event.target.value)} onKeyDown={(event) => { if (event.key === 'Enter' && question.trim()) onNewSession(); }} placeholder="Ask a question..." className="min-w-0 flex-1 bg-transparent text-[11px] text-navy-900 outline-none placeholder:text-ink-500" /><button type="button" onClick={onNewSession} aria-label="Send question" className="text-mint-700"><Send className="h-4 w-4" /></button></label></section>
          </aside>

          <div className="min-w-0">
            <SectionHeading title="My widgets" onViewAll={onOpenReports} />
            {isNewUser ? <EmptyDashboard onAddWidget={onOpenReports} /> : <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{myWidgets.map((widget) => <WidgetCard key={widget.id} widget={widget} />)}</div>}
            <div className="mt-8"><SectionHeading title="Recommended for you" onViewAll={onOpenReports} />{isNewUser ? <div className="rounded-xl border border-surface-200 bg-white px-5 py-5"><div className="flex items-center gap-3"><span className="flex h-9 w-9 items-center justify-center rounded-full bg-mint-100 text-mint-700"><Sparkles className="h-4 w-4" /></span><div><h3 className="text-[12px] font-bold text-navy-900">Recommendations will appear here</h3><p className="mt-1 text-[11px] text-ink-500">As you explore and use ReportIQ, we'll recommend widgets and reports tailored to your needs.</p></div></div></div> : <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{recommendedWidgets.map((widget) => <WidgetCard key={widget.id} widget={widget} recommended added={addedWidgets.includes(widget.id)} onAdd={() => addWidget(widget.id)} />)}</div>}</div>
          </div>
        </div>
      </div>
    </main>
  );
}

function SideCard({ title, icon, onViewAll, children }: { title: string; icon: ReactNode; onViewAll: () => void; children: ReactNode }) { return <section className="rounded-xl border border-surface-200 bg-white px-4 py-3 shadow-[0_2px_8px_rgba(14,42,59,0.03)]"><div className="flex items-center justify-between gap-2"><div className="flex items-center gap-2 text-navy-900">{icon}<h2 className="font-display text-[12px] font-bold">{title}</h2></div><button type="button" onClick={onViewAll} className="text-[10px] font-bold text-mint-700 hover:text-mint-600">View all <span aria-hidden>›</span></button></div><div className="mt-2">{children}</div></section>; }
function SectionHeading({ title, onViewAll }: { title: string; onViewAll: () => void }) { return <div className="mb-3 flex items-center justify-between"><h2 className="font-display text-[17px] font-bold tracking-[-0.03em] text-navy-900">{title}</h2><button type="button" onClick={onViewAll} className="text-[11px] font-bold text-mint-700 hover:text-mint-600">View all <span aria-hidden>›</span></button></div>; }
function EmptySideState({ icon, title, text, action, onAction }: { icon: ReactNode; title: string; text: string; action: string; onAction: () => void }) { return <div className="flex flex-col items-center px-2 py-7 text-center"><span className="text-mint-300">{icon}</span><h3 className="mt-3 text-[12px] font-bold text-navy-900">{title}</h3><p className="mt-1 max-w-[190px] text-[11px] leading-5 text-ink-500">{text}</p><button type="button" onClick={onAction} className="mt-3 rounded-lg border border-mint-300 px-3 py-2 text-[11px] font-bold text-mint-700 hover:bg-mint-50">{action}</button></div>; }
function EmptyDashboard({ onAddWidget }: { onAddWidget: () => void }) { return <div className="flex min-h-[430px] flex-col items-center justify-center rounded-xl border border-surface-200 bg-white px-6 text-center"><span className="flex h-16 w-16 items-center justify-center rounded-2xl bg-mint-50 text-mint-600"><LineChart className="h-9 w-9" /></span><h3 className="mt-5 font-display text-[17px] font-bold text-navy-900">Your dashboard is waiting for you</h3><p className="mt-2 max-w-[320px] text-[12px] leading-5 text-ink-500">Add widgets to your home to track the metrics that matter most to you.</p><button type="button" onClick={onAddWidget} className="mt-5 inline-flex items-center gap-2 rounded-lg bg-[#05aa70] px-4 py-2.5 text-[12px] font-bold text-white hover:bg-[#04945f]"><Plus className="h-4 w-4" /> Add your first widget</button><div className="my-4 flex w-full max-w-[280px] items-center gap-3 text-[11px] text-ink-300"><span className="h-px flex-1 bg-surface-200" />or<span className="h-px flex-1 bg-surface-200" /></div><button type="button" onClick={onAddWidget} className="inline-flex items-center gap-2 rounded-lg border border-surface-200 px-4 py-2.5 text-[11px] font-bold text-navy-900 hover:bg-surface-50"><BarChart3 className="h-4 w-4" /> Explore widget catalogue</button></div>; }

function WidgetCard({ widget, recommended = false, added = false, onAdd }: { widget: Widget; recommended?: boolean; added?: boolean; onAdd?: () => void }) { return <article className="group flex min-h-[190px] flex-col rounded-xl border border-surface-200 bg-white p-3.5 shadow-[0_2px_8px_rgba(14,42,59,0.03)] transition hover:-translate-y-0.5 hover:border-mint-300 hover:shadow-floaty"><div className="flex items-start justify-between gap-2"><span className={`rounded-md px-2 py-1 text-[9px] font-bold tracking-wide ${kindStyles[widget.kind]}`}>{widget.kind}</span><button type="button" aria-label={`More options for ${widget.title}`} className="text-[16px] font-bold leading-none text-navy-900 opacity-70 hover:opacity-100">•••</button></div><h3 className="mt-2 text-[12px] font-bold text-navy-900">{widget.title}</h3><p className="mt-1 min-h-4 text-[10px] text-ink-500">{widget.description}</p><WidgetPreview widget={widget} /><div className="mt-2 flex items-center gap-1.5 text-[9px] text-ink-500"><span className="flex h-4 w-4 items-center justify-center rounded-full bg-surface-100 text-[7px] font-bold text-navy-900">{widget.initials}</span><span className="truncate">{widget.owner}</span><span>·</span><span className="truncate">{widget.updated}</span></div>{recommended ? <button type="button" onClick={onAdd} disabled={added} className="mt-3 inline-flex items-center justify-center gap-1.5 rounded-md border border-surface-200 py-1.5 text-[10px] font-bold text-navy-900 hover:border-mint-300 hover:bg-mint-50 disabled:text-mint-700">{added ? <><LockKeyhole className="h-3 w-3" /> Added to home</> : <><Plus className="h-3 w-3" /> Add to home</>}</button> : <div className="mt-2 flex items-center gap-1 text-[9px] font-semibold text-mint-700">{widget.privacy === 'Private' ? <LockKeyhole className="h-3 w-3" /> : <UsersRound className="h-3 w-3" />}{widget.privacy}</div>}</article>; }

const kindStyles: Record<WidgetKind, string> = { KPI: 'bg-mint-100 text-mint-700', TABLE: 'bg-mint-100 text-mint-700', CHART: 'bg-[#eeebff] text-[#5e55ce]' };

function WidgetPreview({ widget }: { widget: Widget }) { if (widget.kind === 'KPI') return <div className="mt-3 flex items-end justify-between gap-2"><div><div className="font-display text-[23px] font-bold tracking-[-0.04em] text-navy-900">{widget.value}</div><div className={`mt-1 text-[9px] font-bold ${widget.changeDirection === 'down' ? 'text-mint-700' : 'text-mint-700'}`}>{widget.changeDirection === 'down' ? '↓' : '↑'} {widget.change}</div></div><MiniLine /></div>; if (widget.preview === 'table') return <div className="mt-3 overflow-hidden rounded-md border border-surface-100 text-[8px]"><div className="grid grid-cols-3 bg-surface-50 px-2 py-1 font-bold text-ink-500"><span>Product</span><span>Approval</span><span>Trend</span></div>{['Personal Loan', 'Home Loan', 'Vehicle Loan', 'Business Loan'].map((row, index) => <div key={row} className="grid grid-cols-3 border-t border-surface-100 px-2 py-1 text-ink-700"><span className="truncate">{row}</span><span>{['83.6%', '76.4%', '72.1%', '68.3%'][index]}</span><span className="text-mint-600">↗</span></div>)}</div>; if (widget.preview === 'donut') return <div className="mt-3 flex items-center justify-center gap-3"><div className={`donut-chart ${widget.accent}`} /><div className="space-y-1 text-[8px] text-ink-500"><div><i className="legend-dot bg-[#5d55dc]" /> North 42%</div><div><i className="legend-dot bg-[#8178ea]" /> West 28%</div><div><i className="legend-dot bg-[#afa9f4]" /> South 19%</div></div></div>; if (widget.preview === 'bars') return <div className="mt-3 flex h-14 items-end gap-1.5 px-1">{[20, 39, 28, 52, 64, 43, 31].map((height, index) => <span key={index} className="flex-1 rounded-t-sm bg-[#9ba4ef]" style={{ height: `${height}%` }} />)}</div>; return <div className="mt-3 flex h-14 items-end"><MiniLine large /></div>; }
function MiniLine({ large = false }: { large?: boolean }) { return <svg className={large ? 'h-14 w-full' : 'h-12 w-20'} viewBox="0 0 120 50" fill="none" aria-hidden="true"><path d="M2 43C15 39 17 34 28 35C38 36 40 28 51 29C63 30 65 18 75 22C85 26 89 15 99 18C106 20 111 10 118 5V50H2Z" fill="#d8f7eb" /><path d="M2 43C15 39 17 34 28 35C38 36 40 28 51 29C63 30 65 18 75 22C85 26 89 15 99 18C106 20 111 10 118 5" stroke="#0caf78" strokeWidth="2" /></svg>; }
