import { useMemo, useState } from 'react';
import { ArrowLeft, ArrowRight, Check, Database, X } from 'lucide-react';
import { mockSchema, type ParameterInputType, type ReportParameter } from '@/data/reportTemplates';

export function PublishReportDialog({ onClose, onPublished }: { onClose: () => void; onPublished: (parameters: ReportParameter[]) => void }) {
  const [step, setStep] = useState<1 | 2>(1);
  const [selected, setSelected] = useState<string[]>(['loans.disbursed_at', 'branches.region']);
  const [parameters, setParameters] = useState<ReportParameter[]>([]);
  const selectedColumns = useMemo(() => mockSchema.flatMap((table) => table.columns.filter((column) => selected.includes(`${table.name}.${column.name}`)).map((column) => ({ table, column }))), [selected]);

  function configure() {
    setParameters(selectedColumns.map(({ table, column }) => ({ id: `${table.name}-${column.name}`, table: table.name, column: column.name, label: column.label, type: column.suggestedType, required: false, options: column.options, defaultValue: column.suggestedType === 'multi-select' || column.suggestedType === 'date-range' ? [] : '' })));
    setStep(2);
  }

  return <div className="fixed inset-0 z-[70] flex items-center justify-center bg-navy-900/55 p-4" role="dialog" aria-modal="true" aria-labelledby="publish-title">
    <div className="flex max-h-[88vh] w-full max-w-3xl flex-col overflow-hidden rounded-[20px] bg-white shadow-2xl">
      <header className="flex items-center justify-between border-b border-surface-200 px-6 py-4"><div><p className="text-[11px] font-bold uppercase tracking-[0.12em] text-mint-700">Step {step} of 2</p><h2 id="publish-title" className="mt-1 font-display text-[20px] font-bold text-ink-900">{step === 1 ? 'Choose report parameters' : 'Configure inputs'}</h2></div><button onClick={onClose} aria-label="Close publish dialog" className="flex h-9 w-9 items-center justify-center rounded-full text-ink-500 hover:bg-background"><X className="h-4 w-4" /></button></header>
      <div className="min-h-0 flex-1 overflow-y-auto p-6">
        {step === 1 ? <div><p className="text-[13px] leading-relaxed text-ink-500">Select fields from the connected schema that report consumers can change before running this report.</p><div className="mt-5 flex flex-col gap-4">{mockSchema.map((table) => <fieldset key={table.name} className="rounded-[14px] border border-surface-200 p-4"><legend className="px-2 text-[12px] font-bold text-ink-900"><span className="inline-flex items-center gap-2"><Database className="h-4 w-4 text-mint-600" />{table.label}</span></legend><div className="grid gap-2 sm:grid-cols-2">{table.columns.map((column) => { const key = `${table.name}.${column.name}`; return <label key={key} className={`flex cursor-pointer items-center gap-3 rounded-[11px] border p-3 ${selected.includes(key) ? 'border-mint-400 bg-mint-50' : 'border-surface-200'}`}><input type="checkbox" checked={selected.includes(key)} onChange={() => setSelected((current) => current.includes(key) ? current.filter((item) => item !== key) : [...current, key])} className="accent-emerald-500" /><span><span className="block text-[12px] font-bold text-ink-700">{column.label}</span><span className="text-[10px] text-ink-300">{column.name} · {column.suggestedType}</span></span></label>; })}</div></fieldset>)}</div></div> : <div className="flex flex-col gap-3">{parameters.map((parameter, index) => <div key={parameter.id} className="grid gap-3 rounded-[14px] border border-surface-200 p-4 md:grid-cols-[1fr_170px_auto]"><label className="text-[11px] font-bold text-ink-500">Display label<input value={parameter.label} onChange={(event) => setParameters((current) => current.map((item, itemIndex) => itemIndex === index ? { ...item, label: event.target.value } : item))} className="input mt-1.5 text-[12px]" /></label><label className="text-[11px] font-bold text-ink-500">Input type<select value={parameter.type} onChange={(event) => setParameters((current) => current.map((item, itemIndex) => itemIndex === index ? { ...item, type: event.target.value as ParameterInputType } : item))} className="input mt-1.5 text-[12px]"><option value="date">Date</option><option value="date-range">Date range</option><option value="single-select">Single select</option><option value="multi-select">Multi select</option><option value="number">Number</option><option value="text">Text</option></select></label><label className="flex items-center gap-2 self-end pb-2 text-[11px] font-bold text-ink-700"><input type="checkbox" checked={parameter.required} onChange={(event) => setParameters((current) => current.map((item, itemIndex) => itemIndex === index ? { ...item, required: event.target.checked } : item))} className="accent-emerald-500" />Required</label></div>)}</div>}
      </div>
      <footer className="flex items-center justify-between border-t border-surface-200 bg-surface-tertiary px-6 py-4"><button onClick={() => step === 2 ? setStep(1) : onClose()} className="inline-flex items-center gap-2 rounded-[11px] px-4 py-2.5 text-[12px] font-bold text-ink-500 hover:bg-white"><ArrowLeft className="h-4 w-4" />{step === 2 ? 'Back' : 'Cancel'}</button>{step === 1 ? <button disabled={selected.length === 0} onClick={configure} className="inline-flex items-center gap-2 rounded-[11px] bg-navy-900 px-4 py-2.5 text-[12px] font-bold text-white disabled:opacity-40">Configure {selected.length} inputs<ArrowRight className="h-4 w-4" /></button> : <button onClick={() => onPublished(parameters)} className="inline-flex items-center gap-2 rounded-[11px] bg-mint-400 px-4 py-2.5 text-[12px] font-bold text-navy-900 hover:bg-mint-300"><Check className="h-4 w-4" />Publish report</button>}</footer>
    </div>
  </div>;
}
