import { useState } from 'react';
import { ArrowLeft, ArrowRight, BarChart3, BookOpen, FileText, LayoutDashboard, Plus, Search, SlidersHorizontal } from 'lucide-react';
import { catalogueReports, myReports, reportTemplates, type ReportTemplate } from '@/data/reportTemplates';

export function ReportsHub({ onBack, onBuild, onOpenTemplate }: { onBack: () => void; onBuild: () => void; onOpenTemplate: (template: ReportTemplate) => void }) {
  const [tab, setTab] = useState<'mine' | 'catalogue'>('mine');
  const [category, setCategory] = useState('All');
  const categories = ['All', 'Statements', 'Transactions', 'Balance', 'Spending', 'Tax & Audit'];

  return <div className="flex h-full flex-col bg-[#f5f5f7]">
    <div className="border-b border-[#e5e5e7] bg-white px-8 py-5"><div className="flex items-center justify-between"><div className="flex items-center gap-3"><button onClick={onBack} className="flex h-8 w-8 items-center justify-center rounded-full text-ink-500 hover:bg-[#f5f5f7] hover:text-ink-900"><ArrowLeft className="h-4 w-4" /></button><span className="text-[13px] text-ink-500">Reports /</span><h1 className="font-display text-[20px] font-bold tracking-[-0.03em] text-ink-900">{tab === 'mine' ? 'My reports' : 'Catalogue'}</h1></div><div className="flex items-center gap-2"><div className="inline-flex rounded-[12px] border border-[#e5e5e7] bg-[#f5f5f7] p-1"><button onClick={() => setTab('mine')} className={`rounded-[9px] px-3.5 py-1.5 text-[13px] font-semibold ${tab === 'mine' ? 'bg-[#1d1d1f] text-white shadow-soft' : 'text-ink-500'}`}>My reports</button><button onClick={() => setTab('catalogue')} className={`rounded-[9px] px-3.5 py-1.5 text-[13px] font-semibold ${tab === 'catalogue' ? 'bg-[#1d1d1f] text-white shadow-soft' : 'text-ink-500'}`}>Catalogue</button></div></div></div></div>
    {tab === 'mine' ? <MyReports onBuild={onBuild} onOpenTemplate={onOpenTemplate} /> : <Catalogue category={category} categories={categories} setCategory={setCategory} onOpenTemplate={onOpenTemplate} />}
  </div>;
}

function MyReports({ onBuild, onOpenTemplate }: { onBuild: () => void; onOpenTemplate: (template: ReportTemplate) => void }) { return <main className="mx-auto w-full max-w-6xl flex-1 overflow-y-auto px-6 py-5"><div className="flex items-center justify-between gap-4"><div><div className="text-[11px] font-bold uppercase tracking-[0.14em] text-mint-700">Your workspace</div><h2 className="mt-1.5 font-display text-[24px] font-bold tracking-[-0.04em] text-ink-900">Reports made for your team.</h2><p className="mt-1.5 text-[13px] text-ink-500">Pick up a draft, revisit a published report, or start a new conversation.</p></div><div className="flex items-center gap-2 rounded-lg border border-[#e5e5e7] bg-white px-3 py-1.5 text-ink-300"><Search className="h-4 w-4" /><input className="w-40 bg-transparent text-[13px] outline-none placeholder:text-ink-300" placeholder="Search my reports" /></div></div><div className="mt-5 grid grid-cols-2 gap-3 lg:grid-cols-4"><button onClick={onBuild} className="group flex min-h-[172px] flex-col justify-between rounded-lg border border-dashed border-mint-300 bg-mint-50/60 p-4 text-left transition hover:border-mint-400 hover:bg-mint-50"><span className="flex h-8 w-8 items-center justify-center rounded-md bg-mint-400 text-navy-900"><Plus className="h-4 w-4" /></span><span><span className="block text-[14px] font-bold text-navy-900">New report from a template</span><span className="mt-1 block text-[12px] leading-4 text-ink-500">Choose a layout and make it yours.</span></span><span className="text-[11px] font-semibold text-mint-700 group-hover:text-mint-600">Start building →</span></button>{myReports.map((report, index) => <button key={report.id} onClick={() => onOpenTemplate(reportTemplates[index === 1 ? 0 : 1])} className="group flex min-h-[172px] flex-col rounded-lg border border-[#e5e5e7] bg-white p-4 text-left shadow-[0_2px_8px_rgba(0,0,0,0.03)] transition hover:-translate-y-1 hover:border-mint-300 hover:shadow-floaty"><div className="flex items-center justify-between"><span className="flex h-8 w-8 items-center justify-center rounded-md bg-mint-100 text-mint-700">{report.type === 'Chart' ? <BarChart3 className="h-4 w-4" /> : report.type === 'Dashboard' ? <LayoutDashboard className="h-4 w-4" /> : <FileText className="h-4 w-4" />}</span><span className={`rounded-full px-2 py-1 text-[10px] font-bold ${report.status === 'Draft' ? 'bg-amber-100 text-amber-800' : 'bg-mint-100 text-mint-700'}`}>{report.status}</span></div><h3 className="mt-3 font-display text-[15px] font-bold tracking-[-0.02em] text-ink-900">{report.title}</h3><p className="mt-2 flex-1 text-[13px] leading-relaxed text-ink-500">{report.description}</p><div className="mt-5 flex items-center justify-between text-[11px] font-medium text-ink-300"><span>{report.updated}</span><ArrowRight className="h-4 w-4 transition group-hover:translate-x-1 group-hover:text-mint-600" /></div></button>)}</div></main>; }

function Catalogue({ category, categories, setCategory, onOpenTemplate }: { category: string; categories: string[]; setCategory: (value: string) => void; onOpenTemplate: (template: ReportTemplate) => void }) { const filtered = category === 'All' ? catalogueReports : catalogueReports.filter((report) => report.category === category); return <main className="flex-1 overflow-y-auto px-8 py-5"><div className="flex items-center gap-2 overflow-x-auto pb-4">{categories.map((item) => <button key={item} onClick={() => setCategory(item)} className={`inline-flex shrink-0 items-center gap-1.5 rounded-full border px-3.5 py-2 text-[13px] font-semibold ${category === item ? 'border-navy-900 bg-navy-900 text-white' : 'border-[#d2d2d7] bg-white text-ink-500 hover:border-ink-500'}`}>{item === 'All' ? <SlidersHorizontal className="h-3.5 w-3.5" /> : <BookOpen className="h-3.5 w-3.5" />}{item}</button>)}</div><div className="grid grid-cols-3 gap-5">{filtered.map((report, index) => <button key={report.id} onClick={() => onOpenTemplate(reportTemplates[index % 3])} className="group flex min-h-[230px] flex-col rounded-[16px] border border-[#e5e5e7] bg-white p-5 text-left shadow-[0_2px_8px_rgba(0,0,0,0.03)] transition hover:-translate-y-1 hover:border-mint-300 hover:shadow-floaty"><div className="flex items-start gap-3"><span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-[11px] bg-[#fff1f0] text-red-500"><FileText className="h-5 w-5" /></span><div><h3 className="font-display text-[15px] font-bold tracking-[-0.02em] text-ink-900">{report.title}</h3><p className="mt-1 text-[12px] text-ink-500">{report.owner}</p></div></div><p className="mt-5 flex-1 text-[13px] leading-relaxed text-ink-500">{report.description}</p><div className="mt-4 flex items-center gap-2"><span className="rounded-full bg-mint-100 px-2.5 py-1 text-[11px] font-semibold text-mint-700">{report.cadence}</span><span className="rounded-full bg-[#f5f5f7] px-2.5 py-1 text-[11px] font-semibold text-ink-500">{report.format}</span><ArrowRight className="ml-auto h-4 w-4 text-ink-300 transition group-hover:translate-x-1 group-hover:text-mint-600" /></div></button>)}</div></main>; }
