import { useMemo, useState } from 'react';
import { ArrowLeft, ArrowRight, BarChart3, BookOpen, ChevronDown, FileText, Filter, Grid2X2, List, MoreHorizontal, Plus, Search, Share2, Trash2, Pencil, Copy, ExternalLink, type LucideIcon } from 'lucide-react';
import { reportTemplates, type ReportTemplate } from '@/data/reportTemplates';

type Report = { id: string; title: string; description: string; owner: string; initials: string; updated: string; status: 'Published' | 'Draft'; icon: 'file' | 'chart' | 'grid' };
const reports: Report[] = [
  { id: 'q2', title: 'Q2 branch review', description: 'Comprehensive review of branch performance and key metrics for Q2.', owner: 'You', initials: 'RA', updated: '2h ago', status: 'Published', icon: 'file' },
  { id: 'loan', title: 'Loan portfolio summary', description: 'Summary of loan portfolio performance and key trends.', owner: 'You', initials: 'RA', updated: 'yesterday', status: 'Draft', icon: 'chart' },
  { id: 'npa', title: 'NPA trend analysis', description: 'Trend of gross and net NPA across time periods.', owner: 'Anita Gupta', initials: 'AG', updated: '1d ago', status: 'Published', icon: 'grid' },
  { id: 'collections', title: 'Collection efficiency report', description: 'Analysis of collection efficiency and bucket performance.', owner: 'Rohit Mehta', initials: 'RM', updated: '2d ago', status: 'Published', icon: 'chart' },
  { id: 'segments', title: 'Customer segment performance', description: 'Performance of customer segments across key metrics.', owner: 'Sneha Banerjee', initials: 'SB', updated: '3d ago', status: 'Draft', icon: 'file' },
  { id: 'risk', title: 'High risk accounts overview', description: 'Overview of high risk accounts and outstanding amounts.', owner: 'Rohit Mehta', initials: 'RM', updated: '4d ago', status: 'Published', icon: 'chart' },
  { id: 'mix', title: 'Product mix analysis', description: 'Distribution of disbursals by product category.', owner: 'Anita Gupta', initials: 'AG', updated: '5d ago', status: 'Published', icon: 'grid' },
  { id: 'ops', title: 'Operational KPI dashboard', description: 'Key operational KPIs and performance tracker.', owner: 'You', initials: 'RA', updated: '6d ago', status: 'Draft', icon: 'chart' },
];
const categories = ['Category', 'Owner', 'Created', 'Updated'];

export function ReportsHub({ onBack, onBuild, onOpenTemplate }: { onBack: () => void; onBuild: () => void; onOpenTemplate: (template: ReportTemplate) => void }) {
  const [tab, setTab] = useState<'mine' | 'catalogue' | 'shared'>('mine');
  const [query, setQuery] = useState('');
  const [menu, setMenu] = useState<string | null>(null);
  const filtered = useMemo(() => reports.filter((report) => `${report.title} ${report.owner} ${report.description}`.toLowerCase().includes(query.toLowerCase())), [query]);
  return <div className="flex h-full flex-col bg-white text-navy-900">
    <header className="border-b border-surface-200 bg-white px-6 pb-0 pt-5 lg:px-8"><div className="flex items-start justify-between gap-6"><div><div className="flex items-center gap-2"><button onClick={onBack} className="mr-1 flex h-7 w-7 items-center justify-center rounded-md text-ink-500 hover:bg-surface-100"><ArrowLeft className="h-4 w-4" /></button><h1 className="font-display text-[25px] font-bold tracking-[-0.04em]">Browse reports</h1></div><p className="mt-1 pl-9 text-[13px] text-ink-500">Find, manage and access your reports.</p></div><div className="flex items-center gap-3"><label className="hidden w-[380px] items-center gap-2 rounded-lg border border-surface-200 bg-white px-3 py-2.5 text-ink-300 md:flex"><Search className="h-4 w-4" /><span className="sr-only">Search reports</span><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search reports by name, owner or description..." className="min-w-0 flex-1 text-[12px] text-navy-900 outline-none placeholder:text-ink-400" /></label><button onClick={onBuild} className="inline-flex items-center gap-2 rounded-lg bg-[#132a3a] px-4 py-2.5 text-[12px] font-bold text-white hover:bg-[#0d202d]"><Plus className="h-4 w-4" /> New report</button></div></div><nav className="mt-7 flex gap-7"><Tab active={tab === 'mine'} onClick={() => setTab('mine')}>My reports</Tab><Tab active={tab === 'catalogue'} onClick={() => setTab('catalogue')}>Reports catalogue</Tab><Tab active={tab === 'shared'} onClick={() => setTab('shared')}>Shared with me</Tab></nav></header>
    <main className="flex-1 overflow-y-auto px-6 py-5 lg:px-8"><div className="flex flex-wrap items-center gap-3"><button className="inline-flex items-center gap-2 rounded-lg border border-surface-200 px-4 py-2.5 text-[12px] font-bold text-navy-900 hover:bg-surface-50"><Filter className="h-4 w-4" /> Filters</button>{categories.map((label) => <button key={label} className="inline-flex items-center gap-2 rounded-full border border-surface-200 px-4 py-2.5 text-[12px] font-semibold text-ink-700 hover:border-mint-300 hover:bg-mint-50">{label}<ChevronDown className="h-3.5 w-3.5 text-ink-400" /></button>)}<div className="ml-auto flex items-center gap-2 text-[12px] text-ink-500">Sort by:<button className="inline-flex items-center gap-2 rounded-lg border border-surface-200 px-3 py-2.5 font-bold text-navy-900">Recently updated<ChevronDown className="h-3.5 w-3.5" /></button><button className="flex h-9 w-9 items-center justify-center rounded-lg border border-mint-300 bg-mint-50 text-mint-700"><Grid2X2 className="h-4 w-4" /></button><button className="flex h-9 w-9 items-center justify-center rounded-lg border border-surface-200 text-ink-500"><List className="h-4 w-4" /></button></div></div><p className="mt-5 text-[13px] text-ink-500">24 reports</p><div className="mt-4 grid grid-cols-1 gap-4 sm:grid-cols-2 xl:grid-cols-4">{filtered.map((report, index) => <ReportCard key={report.id} report={report} menuOpen={menu === report.id} onMenu={() => setMenu(menu === report.id ? null : report.id)} onOpen={() => onOpenTemplate(reportTemplates[index % reportTemplates.length])} />)}</div><div className="flex items-center justify-between py-7 text-[12px] text-ink-500"><span>Showing 1–8 of 24 reports</span><div className="flex items-center gap-2"><button className="flex h-9 w-9 items-center justify-center rounded-lg border border-surface-200"><ArrowLeft className="h-4 w-4" /></button><button className="h-9 w-9 rounded-lg border border-mint-400 bg-mint-50 font-bold text-mint-700">1</button>{['2', '3', '…', '6'].map((page) => <button key={page} className="h-9 w-9 rounded-lg border border-surface-200 font-semibold text-navy-900">{page}</button>)}<button className="flex h-9 w-9 items-center justify-center rounded-lg border border-surface-200"><ArrowRight className="h-4 w-4" /></button></div></div></main>
  </div>;
}
function Tab({ active, onClick, children }: { active: boolean; onClick: () => void; children: React.ReactNode }) { return <button onClick={onClick} className={`border-b-2 px-1 pb-3 text-[13px] font-bold transition ${active ? 'border-mint-500 text-mint-700' : 'border-transparent text-ink-500 hover:text-navy-900'}`}>{children}</button>; }
function ReportCard({ report, menuOpen, onMenu, onOpen }: { report: Report; menuOpen: boolean; onMenu: () => void; onOpen: () => void }) { const icon = report.icon === 'chart' ? <BarChart3 className="h-5 w-5" /> : report.icon === 'grid' ? <Grid2X2 className="h-5 w-5" /> : <FileText className="h-5 w-5" />; return <article className="relative flex min-h-[255px] flex-col rounded-lg border border-surface-200 bg-white p-5 shadow-[0_2px_8px_rgba(19,42,58,0.03)] transition hover:-translate-y-0.5 hover:border-mint-300 hover:shadow-floaty"><div className="flex items-start justify-between"><span className={`flex h-10 w-10 items-center justify-center rounded-md ${report.icon === 'chart' ? 'bg-lilac-100 text-lilac-600' : 'bg-mint-100 text-mint-700'}`}>{icon}</span><div className="flex items-center gap-3"><span className={`rounded-full px-2.5 py-1 text-[10px] font-bold ${report.status === 'Published' ? 'bg-mint-100 text-mint-700' : 'bg-amber-100 text-amber-800'}`}>{report.status}</span><button onClick={onMenu} aria-label={`More options for ${report.title}`} className="text-navy-900"><MoreHorizontal className="h-5 w-5" /></button></div></div><h2 className="mt-7 font-display text-[15px] font-bold tracking-[-0.02em] text-navy-900">{report.title}</h2><p className="mt-2 text-[13px] leading-5 text-ink-500">{report.description}</p><div className="mt-auto flex items-center justify-between pt-5 text-[11px] text-ink-500"><span className="flex items-center gap-2"><span className="flex h-6 w-6 items-center justify-center rounded-full border border-surface-300 bg-surface-50 text-[9px] font-bold text-ink-700">{report.initials}</span><span className="font-semibold text-navy-900">{report.owner}</span></span></div>{menuOpen && <ReportMenu onOpen={onOpen} />}</article>; }
function ReportMenu({ onOpen }: { onOpen: () => void }) { const items: Array<[string, LucideIcon]> = [['Open', ExternalLink], ['Edit', Pencil], ['Duplicate', Copy], ['Share', Share2], ['Publish to catalogue', BookOpen], ['Delete', Trash2]]; return <div className="absolute right-4 top-14 z-20 w-44 overflow-hidden rounded-lg border border-surface-200 bg-white py-1 shadow-floaty">{items.map(([label, Icon]) => <button key={String(label)} onClick={label === 'Open' ? onOpen : undefined} className={`flex w-full items-center gap-2 px-3 py-2 text-left text-[11px] font-semibold ${label === 'Delete' ? 'text-red-600 hover:bg-red-50' : 'text-ink-700 hover:bg-mint-50'}`}><Icon className="h-3.5 w-3.5" />{label}</button>)}</div>; }
