import { useMemo, useState } from 'react';
import { ArrowLeft, ArrowRight, BarChart3, Bookmark, BookOpen, CalendarClock, ChevronDown, ExternalLink, FileText, Filter, Grid2X2, List, LockKeyhole, MoreHorizontal, Plus, Search, Play, Share2, Trash2, Pencil, Copy, type LucideIcon } from 'lucide-react';
import { reportTemplates, type ReportTemplate } from '@/data/reportTemplates';
import { useT } from '@/providers/I18nProvider';

type Report = { id: string; title: string; description: string; owner: string; initials: string; updated: string; status: 'Published' | 'Draft'; icon: 'file' | 'chart' | 'grid' };
const reports: Report[] = [
  { id: 'q2', title: 'Q2 branch review', description: 'Comprehensive review of branch performance and key metrics for Q2.', owner: 'You', initials: 'RA', updated: '2h ago', status: 'Published', icon: 'file' },
  { id: 'loan', title: 'Loan portfolio summary', description: 'Summary of loan portfolio performance and key trends.', owner: 'You', initials: 'RA', updated: 'yesterday', status: 'Draft', icon: 'chart' },
  { id: 'npa', title: 'NPA trend analysis', description: 'Trend of gross and net NPA across time periods.', owner: 'Anita Gupta', initials: 'AG', updated: '1d ago', status: 'Published', icon: 'grid' },
  { id: 'collections', title: 'Collection efficiency report', description: 'Analysis of collection efficiency and bucket performance.', owner: 'Rohit Mehta', initials: 'RM', updated: '2d ago', status: 'Published', icon: 'chart' },
  { id: 'segments', title: 'Customer segment performance', description: 'Performance of customer segments across key metrics.', owner: 'Sneha Banerjee', initials: 'SB', updated: '3d ago', status: 'Draft', icon: 'file' },
  { id: 'risk', title: 'High risk accounts overview', description: 'Overview of high risk accounts and outstanding amounts.', owner: 'Rohit Mehta', initials: 'RM', updated: '4d ago', status: 'Published', icon: 'chart' },
  { id: 'mix', title: 'Product mix analysis', description: 'Distribution of disbursals by product category.', owner: 'Anita Gupta', initials: 'AG', updated: '5d ago', status: 'Published', icon: 'grid' },
  { id: 'ops', title: 'Operational KPI dashboard', description: 'Key operational KPIs and performance tracker.', owner: 'You', initials: 'RA', updated: '6d ago', status: 'Draft', icon: 'chart' },
];

export function ReportsHub({ onBack, onBuild, onOpenTemplate }: { onBack: () => void; onBuild: (template?: ReportTemplate) => void; onOpenTemplate: (template: ReportTemplate) => void }) {
  const t = useT();
  const [tab, setTab] = useState<'mine' | 'catalogue' | 'shared'>('mine');
  const [query, setQuery] = useState('');
  const [menu, setMenu] = useState<string | null>(null);
  const [homeReports, setHomeReports] = useState<string[]>([]);
  const filtered = useMemo(() => reports.filter((report) => `${report.title} ${report.owner} ${report.description}`.toLowerCase().includes(query.toLowerCase())), [query]);
  const categoryLabels = [t('common.category'), t('common.owner'), t('common.created'), t('common.updated')];
  return <div className="flex h-full flex-col bg-white text-navy-900">
    <header className="border-b border-surface-200 bg-white px-6 pb-0 pt-5 lg:px-8"><div className="flex items-start justify-between gap-6"><div><div className="flex items-center gap-2"><button onClick={onBack} className="mr-1 flex h-7 w-7 items-center justify-center rounded-md text-ink-500 hover:bg-surface-100"><ArrowLeft className="h-4 w-4" /></button><h1 className="font-display text-[25px] font-bold tracking-[-0.04em]">{t('reports.browse')}</h1></div><p className="mt-1 pl-9 text-[13px] text-ink-500">{t('reports.subtitle')}</p></div><div className="flex items-center gap-3"><label className="hidden w-[380px] items-center gap-2 rounded-lg border border-surface-200 bg-white px-3 py-2.5 text-ink-300 md:flex"><Search className="h-4 w-4" /><span className="sr-only">{t('reports.searchLabel')}</span><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder={t('reports.searchPlaceholder')} className="min-w-0 flex-1 text-[12px] text-navy-900 outline-none placeholder:text-ink-400" /></label><button onClick={() => onBuild()} className="inline-flex items-center gap-2 rounded-lg bg-navy-900 px-4 py-2.5 text-[12px] font-bold text-white hover:bg-navy-800"><Plus className="h-4 w-4" /> {t('reports.newReport')}</button></div></div><nav className="mt-7 flex gap-7"><Tab active={tab === 'mine'} onClick={() => setTab('mine')}>{t('reports.myReports')}</Tab><Tab active={tab === 'catalogue'} onClick={() => setTab('catalogue')}>{t('reports.catalogue')}</Tab><Tab active={tab === 'shared'} onClick={() => setTab('shared')}>{t('reports.sharedWithMe')}</Tab></nav></header>
    <main className="flex-1 overflow-y-auto px-6 py-5 lg:px-8"><div className="flex flex-wrap items-center gap-3"><button className="inline-flex items-center gap-2 rounded-lg border border-surface-200 px-4 py-2.5 text-[12px] font-bold text-navy-900 hover:bg-surface-50"><Filter className="h-4 w-4" /> {t('common.filters')}</button>{categoryLabels.map((label) => <button key={label} className="inline-flex items-center gap-2 rounded-full border border-surface-200 px-4 py-2.5 text-[12px] font-semibold text-ink-700 hover:border-mint-300 hover:bg-mint-50">{label}<ChevronDown className="h-3.5 w-3.5 text-ink-400" /></button>)}<div className="ml-auto flex items-center gap-2 text-[12px] text-ink-500">{t('common.sortBy')}<button className="inline-flex items-center gap-2 rounded-lg border border-surface-200 px-3 py-2.5 font-bold text-navy-900">{t('common.recentlyUpdated')}<ChevronDown className="h-3.5 w-3.5" /></button><button className="flex h-9 w-9 items-center justify-center rounded-lg border border-mint-300 bg-mint-50 text-mint-700"><Grid2X2 className="h-4 w-4" /></button><button className="flex h-9 w-9 items-center justify-center rounded-lg border border-surface-200 text-ink-500"><List className="h-4 w-4" /></button></div></div><p className="mt-5 text-[13px] text-ink-500">{t('reports.reportCount')}</p><div className="mt-4 grid grid-cols-1 gap-4 sm:grid-cols-2 xl:grid-cols-4">{filtered.map((report, index) => <ReportCard key={report.id} report={report} menuOpen={menu === report.id} onMenu={() => setMenu(menu === report.id ? null : report.id)} onOpen={() => onOpenTemplate(reportTemplates[index % reportTemplates.length])} onRun={() => onOpenTemplate(reportTemplates[index % reportTemplates.length])} onEdit={() => onBuild(reportTemplates[index % reportTemplates.length])} added={homeReports.includes(report.id)} onAdd={() => setHomeReports((current) => current.includes(report.id) ? current : [...current, report.id])} />)}</div><div className="flex items-center justify-between py-7 text-[12px] text-ink-500"><span>{t('reports.showingRange')}</span><div className="flex items-center gap-2"><button className="flex h-9 w-9 items-center justify-center rounded-lg border border-surface-200"><ArrowLeft className="h-4 w-4" /></button><button className="h-9 w-9 rounded-lg border border-mint-400 bg-mint-50 font-bold text-mint-700">1</button>{['2', '3', '…', '6'].map((page) => <button key={page} className="h-9 w-9 rounded-lg border border-surface-200 font-semibold text-navy-900">{page}</button>)}<button className="flex h-9 w-9 items-center justify-center rounded-lg border border-surface-200"><ArrowRight className="h-4 w-4" /></button></div></div></main>
  </div>;
}
function Tab({ active, onClick, children }: { active: boolean; onClick: () => void; children: React.ReactNode }) { return <button onClick={onClick} className={`border-b-2 px-1 pb-3 text-[13px] font-bold transition ${active ? 'border-mint-500 text-mint-700' : 'border-transparent text-ink-500 hover:text-navy-900'}`}>{children}</button>; }
function ReportCard({ report, menuOpen, onMenu, onOpen, onRun, onEdit, added, onAdd }: { report: Report; menuOpen: boolean; onMenu: () => void; onOpen: () => void; onRun: () => void; onEdit: () => void; added: boolean; onAdd: () => void }) {
  const t = useT();
  const icon = report.icon === 'chart' ? <BarChart3 className="h-5 w-5" /> : report.icon === 'grid' ? <Grid2X2 className="h-5 w-5" /> : <FileText className="h-5 w-5" />;
  return <article className="relative flex min-h-[255px] flex-col rounded-lg border border-surface-200 bg-white p-5 shadow-card-dark transition hover:-translate-y-0.5 hover:border-mint-300 hover:shadow-floaty"><div className="flex items-start justify-between"><span className={`flex h-10 w-10 items-center justify-center rounded-md ${report.icon === 'chart' ? 'bg-badge-purple-bg text-badge-purple-text' : 'bg-mint-100 text-mint-700'}`}>{icon}</span><div className="flex items-start gap-3"><span className={`rounded-full px-2.5 py-1 text-[10px] font-bold ${report.status === 'Published' ? 'bg-mint-100 text-mint-700' : 'bg-amber-100 text-amber-800'}`}>{report.status === 'Published' ? t('reports.published') : t('reports.draft')}</span><button onClick={onRun} aria-label={t('reports.runReportName', { name: report.title })} className="flex h-8 w-8 items-center justify-center text-navy-900 hover:text-mint-700" title={t('reports.runReport')}><Play className="h-3.5 w-3.5" /></button></div></div><h2 className="mt-7 font-display text-[15px] font-bold tracking-[-0.02em] text-navy-900">{report.title}</h2><p className="mt-2 text-[13px] leading-5 text-ink-500">{report.description}</p><div className="mt-auto flex flex-col gap-4 pt-5 text-[11px] text-ink-500"><div className="flex items-center justify-between"><span className="flex items-center gap-2"><span className="flex h-9 w-9 items-center justify-center rounded-full border border-surface-200 bg-surface-100 text-[11px] font-bold text-navy-900">{report.initials}</span><span className="font-semibold text-ink-500">{report.owner} · {t('reports.updatedMeta', { time: report.updated })}</span></span><span className="inline-flex items-center gap-1.5 font-bold text-mint-700"><LockKeyhole className="h-3.5 w-3.5" /> {t('reports.private')}</span></div><div className="grid grid-cols-[1fr_1fr_auto] gap-3"><button type="button" onClick={onEdit} className="inline-flex items-center justify-center gap-2 rounded-lg border border-surface-200 px-3 py-1.5 text-[11px] font-bold text-navy-900 hover:bg-mint-50"><Pencil className="h-5 w-5" /> {t('common.edit')}</button><button type="button" onClick={onAdd} className={`inline-flex items-center justify-center gap-2 rounded-lg border px-3 py-1.5 text-[11px] font-bold ${added ? 'border-mint-200 bg-mint-50 text-mint-700' : 'border-surface-200 text-navy-900 hover:bg-mint-50'}`}><Bookmark className="h-5 w-5" /> {added ? t('reports.added') : t('reports.addToHome')}</button><button type="button" onClick={onMenu} aria-label={t('reports.moreOptions', { name: report.title })} className="flex h-9 w-9 items-center justify-center rounded-lg border border-surface-200 text-navy-900 hover:bg-surface-50"><MoreHorizontal className="h-5 w-5" /></button></div></div>{menuOpen && <ReportMenu onOpen={onOpen} />}</article>;
}
function ReportMenu({ onOpen }: { onOpen: () => void }) {
  const t = useT();
  const items: Array<[string, LucideIcon]> = [[t('common.duplicate'), Copy], [t('common.share'), Share2], [t('reports.scheduleReport'), CalendarClock], [t('widgets.publishToCatalogue'), BookOpen], [t('common.delete'), Trash2]];
  return <div className="absolute bottom-14 right-4 z-20 w-44 overflow-hidden rounded-lg border border-surface-200 bg-white py-1 shadow-floaty">{items.map(([label, Icon]) => <button key={String(label)} onClick={label === t('common.duplicate') ? onOpen : undefined} className={`flex w-full items-center gap-2 px-3 py-2 text-left text-[11px] font-semibold ${label === t('common.delete') ? 'text-red-600 hover:bg-red-50' : 'text-ink-700 hover:bg-mint-50'}`}><Icon className="h-3.5 w-3.5" />{label}</button>)}</div>;
}
