import { useMemo, useState, type ReactNode } from 'react';
import { ChartBar as BarChart3, Bookmark, BookmarkMinus, Check, ChevronDown, CreditCard as Edit3, Ellipsis, Eye, Grid2x2X as Grid2X2, LayoutList, MoveHorizontal as MoreHorizontal, Plus, Search, Share2, SlidersHorizontal, Sparkles, Trash2, UsersRound, X } from 'lucide-react';
import { myWidgets, recommendedWidgets, type Widget, type WidgetKind } from '@/data/homeData';
import { useT } from '@/providers/I18nProvider';

type Props = { onBack: () => void; onEditWidget: (widget: Widget) => void; onNewWidget: () => void; homeWidgetIds: string[]; onToggleHomeWidget: (id: string) => void };
type Category = 'All' | 'Lending' | 'Risk' | 'Collections' | 'Sales' | 'Operations';
const categories: Category[] = ['All', 'Lending', 'Risk', 'Collections', 'Sales', 'Operations'];
const catalogueWidgets: Widget[] = [
  { id: 'catalogue-approval', kind: 'TABLE', title: 'Approval rate by product', description: 'Approval rate (%) by product and customer segment.', owner: 'You', initials: 'RA', updated: 'Updated 2h ago', privacy: 'Catalogue', preview: 'table', accent: 'mint' },
  { id: 'catalogue-npa', kind: 'CHART', title: 'NPA trend over time', description: 'Gross NPA (%) trend over the last 12 months.', owner: 'Anita Gupta', initials: 'AG', updated: 'Updated 1d ago', privacy: 'Catalogue', preview: 'line', accent: 'blue' },
  { id: 'catalogue-collection', kind: 'CHART', title: 'Collection efficiency trend', description: 'Collection efficiency (%) trend over time.', owner: 'S. Banerjee', initials: 'SB', updated: 'Updated 5d ago', privacy: 'Catalogue', preview: 'bars', accent: 'violet' },
  { id: 'catalogue-overdue', kind: 'TABLE', title: 'Top overdue accounts', description: 'Top 20 overdue accounts by outstanding amount.', owner: 'You', initials: 'RA', updated: 'Updated 5d ago', privacy: 'Private', preview: 'table', accent: 'mint' },
  ...recommendedWidgets,
];
const sharedWidgets: Widget[] = [
  { id: 'shared-npa', kind: 'CHART', title: 'NPA trend over time', description: 'Gross NPA (%) trend over the last 12 months.', owner: 'Anita Gupta', initials: 'AG', updated: 'Updated 1d ago', privacy: 'Shared', preview: 'line', accent: 'blue' },
  { id: 'shared-collection', kind: 'CHART', title: 'Collection efficiency trend', description: 'Collection efficiency (%) trend over time.', owner: 'Rohit Mehta', initials: 'RM', updated: 'Updated 2d ago', privacy: 'Shared', preview: 'bars', accent: 'violet' },
  { id: 'shared-loan-book', kind: 'CHART', title: 'Loan book by region', description: 'Loan book (%) distribution across regions.', owner: 'Anita Gupta', initials: 'AG', updated: 'Updated 6d ago', privacy: 'Shared', preview: 'donut', accent: 'violet' },
];
const kindStyles: Record<WidgetKind, string> = { TABLE: 'bg-mint-100 text-mint-700', CHART: 'bg-badge-purple-bg text-badge-purple-text' };

export function WidgetsPage({ onBack, onEditWidget, onNewWidget, homeWidgetIds, onToggleHomeWidget }: Props) {
  const t = useT();
  const [tab, setTab] = useState<'mine' | 'catalogue' | 'shared'>('mine');
  const [category, setCategory] = useState<Category>('All');
  const [query, setQuery] = useState('');
  const [sort, setSort] = useState(t('common.recentlyUpdated'));
  const [list, setList] = useState(false);
  const [menuId, setMenuId] = useState<string | null>(null);
  const [shareWidget, setShareWidget] = useState<Widget | null>(null);
  const [publishWidget, setPublishWidget] = useState<Widget | null>(null);
  const [viewWidget, setViewWidget] = useState<Widget | null>(null);
  const [added, setAdded] = useState<string[]>(['disbursed', 'approval', 'npa-trend']);
  const [removedFromHome, setRemovedFromHome] = useState<string[]>([]);
  const source = (tab === 'mine' ? myWidgets : tab === 'catalogue' ? catalogueWidgets : sharedWidgets).filter((widget) => tab !== 'mine' || !removedFromHome.includes(widget.id));
  const widgets = useMemo(() => source.filter((widget) => `${widget.title} ${widget.description} ${widget.owner}`.toLowerCase().includes(query.toLowerCase())), [source, query]);

  function addToHome(id: string) { setAdded((current) => current.includes(id) ? current.filter((item) => item !== id) : [...current, id]); }

  return <main className="min-h-0 flex-1 overflow-y-auto bg-white" onClick={() => menuId && setMenuId(null)}>
    <div className="mx-auto max-w-[1480px] px-5 py-6 sm:px-8 lg:px-10">
      <header className="flex flex-col justify-between gap-4 sm:flex-row sm:items-start"><div><h1 className="font-display text-[25px] font-bold tracking-[-0.04em] text-navy-900">{t('widgets.title')}</h1><p className="mt-1 text-[13px] text-ink-500">{t('widgets.subtitle')}</p></div><div className="flex items-center gap-3"><label className="hidden w-[380px] items-center gap-2 rounded-lg border border-surface-200 bg-white px-3 py-2.5 text-ink-300 md:flex"><Search className="h-4 w-4" /><span className="sr-only">{t('widgets.searchLabel')}</span><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder={t('widgets.searchPlaceholder')} className="min-w-0 flex-1 text-[12px] text-navy-900 outline-none placeholder:text-ink-400" /></label><button type="button" onClick={onNewWidget} className="inline-flex items-center gap-2 rounded-lg bg-navy-900 px-4 py-2.5 text-[12px] font-bold text-white transition hover:bg-navy-800"><Plus className="h-4 w-4" /> {t('widgets.newWidget')}</button></div></header>
      <div className="mt-6 border-b border-surface-200"><div className="flex gap-6"><button type="button" onClick={() => setTab('mine')} className={`border-b-2 px-1 pb-3 text-[12px] font-bold transition ${tab === 'mine' ? 'border-mint-500 text-mint-700' : 'border-transparent text-ink-500 hover:text-navy-900'}`}>{t('widgets.myWidgets')}</button><button type="button" onClick={() => setTab('catalogue')} className={`border-b-2 px-1 pb-3 text-[12px] font-bold transition ${tab === 'catalogue' ? 'border-mint-500 text-mint-700' : 'border-transparent text-ink-500 hover:text-navy-900'}`}>{t('widgets.catalogue')}</button><button type="button" onClick={() => setTab('shared')} className={`border-b-2 px-1 pb-3 text-[12px] font-bold transition ${tab === 'shared' ? 'border-mint-500 text-mint-700' : 'border-transparent text-ink-500 hover:text-navy-900'}`}>{t('widgets.sharedWithMe')}</button></div></div>
      <div className="mt-5 flex flex-wrap items-center gap-3"><button type="button" className="inline-flex items-center gap-2 rounded-lg border border-surface-200 px-4 py-2.5 text-[12px] font-bold text-navy-900 hover:bg-surface-50"><SlidersHorizontal className="h-4 w-4" /> {t('common.filters')}</button>{[t('common.category'), t('common.owner'), t('common.created'), t('common.updated')].map((label) => <button type="button" key={label} className="inline-flex items-center gap-2 rounded-full border border-surface-200 px-4 py-2.5 text-[12px] font-semibold text-ink-700 hover:border-mint-300 hover:bg-mint-50">{label}<ChevronDown className="h-3.5 w-3.5 text-ink-400" /></button>)}<div className="ml-auto flex items-center gap-2 text-[12px] text-ink-500">{t('common.sortBy')}<select value={sort} onChange={(event) => setSort(event.target.value)} className="rounded-lg border border-surface-200 bg-white px-3 py-2.5 font-bold text-navy-900 outline-none"><option>{t('common.recentlyUpdated')}</option><option>{t('common.nameAZ')}</option><option>{t('common.type')}</option></select><div className="flex rounded-lg border border-surface-200 p-0.5"><button type="button" onClick={() => setList(false)} className={`flex h-8 w-9 items-center justify-center rounded-md ${!list ? 'bg-mint-50 text-mint-700' : 'text-ink-500'}`} aria-label={t('widgets.gridView')}><Grid2X2 className="h-4 w-4" /></button><button type="button" onClick={() => setList(true)} className={`flex h-8 w-9 items-center justify-center rounded-md ${list ? 'bg-mint-50 text-mint-700' : 'text-ink-500'}`} aria-label={t('widgets.listView')}><LayoutList className="h-4 w-4" /></button></div></div></div>
      <div className={`mt-5 grid gap-4 ${list ? 'grid-cols-1' : 'sm:grid-cols-2 xl:grid-cols-4'}`}>{widgets.map((widget) => <WidgetCard key={widget.id} widget={widget} menuOpen={menuId === widget.id} onMenu={(event) => { event.stopPropagation(); setMenuId(menuId === widget.id ? null : widget.id); }} added={homeWidgetIds.includes(widget.id)} onAdd={() => onToggleHomeWidget(widget.id)} onShare={() => { setMenuId(null); setShareWidget(widget); }} onPublish={() => { setMenuId(null); setPublishWidget(widget); }} onView={() => setViewWidget(widget)} onEdit={() => onEditWidget(widget)} onRemove={() => onToggleHomeWidget(widget.id)} />)}</div>
      {!widgets.length && <div className="mt-5 rounded-lg border border-dashed border-surface-200 px-6 py-16 text-center text-[13px] text-ink-500">{t('widgets.noMatch')}</div>}
      <div className="flex items-center justify-center gap-4 py-7 text-[11px] text-ink-500">{t('widgets.showingOf', { count: String(widgets.length) })} <button type="button" className="rounded-lg border border-surface-200 px-4 py-2 font-bold text-navy-900 hover:bg-surface-50">{t('common.loadMore')} <ChevronDown className="ml-1 inline h-3.5 w-3.5" /></button></div>
    </div>
    {shareWidget && <ShareWidgetModal widget={shareWidget} onClose={() => setShareWidget(null)} />}
    {publishWidget && <ShareToCatalogueModal widget={publishWidget} onClose={() => setPublishWidget(null)} />}
    {viewWidget && <WidgetReadOnlyView widget={viewWidget} onClose={() => setViewWidget(null)} onEdit={() => onEditWidget(viewWidget)} />}
  </main>;
}

function WidgetCard({ widget, menuOpen, onMenu, onAdd, onShare, onPublish, onView, onEdit, onRemove, added }: { widget: Widget; menuOpen: boolean; onMenu: (event: React.MouseEvent) => void; onAdd: () => void; onShare: () => void; onPublish: () => void; onView: () => void; onEdit: () => void; onRemove: () => void; added: boolean }) {
  const t = useT();
  return <article onClick={onView} className="group relative flex min-h-[300px] cursor-pointer flex-col rounded-lg border border-surface-200 bg-white p-4 shadow-card transition hover:-translate-y-0.5 hover:border-mint-300 hover:shadow-floaty"><div className="flex items-start justify-between gap-2"><span className={`rounded-md px-2 py-1 text-[9px] font-bold tracking-wide ${kindStyles[widget.kind]}`}>{widget.kind}</span><div className="flex items-center gap-2"><button type="button" onClick={(event) => { event.stopPropagation(); onView(); }} aria-label={t('home.previewWidgetName', { name: widget.title })} title={t('home.previewWidget')} className="text-navy-900 transition hover:text-mint-700"><Eye className="h-3.5 w-3.5" aria-hidden="true" /></button></div></div><div className="mt-3 flex items-center justify-between gap-2"><div className="flex items-center gap-2"><h2 className="text-[14px] font-bold tracking-[-0.02em] text-navy-900">{widget.title}</h2></div>{added && <span className="rounded-full border border-mint-200 bg-mint-50 px-2 py-1 text-[9px] font-bold text-mint-700">{t('home.addedToHome')}</span>}</div><p className="mt-1 min-h-8 text-[11px] leading-4 text-ink-500">{widget.description}</p><Preview widget={widget} /><div className="mt-auto flex items-center justify-between gap-2 pt-3 text-[9px] text-ink-500"><span className="flex min-w-0 items-center gap-1.5"><span className="flex h-5 w-5 shrink-0 items-center justify-center rounded-full bg-surface-100 text-[8px] font-bold text-navy-900">{widget.initials}</span><span className="truncate">{widget.owner} · {widget.updated}</span></span><span className={`flex shrink-0 items-center gap-1 font-bold ${widget.privacy === 'Private' ? 'text-mint-700' : 'text-badge-purple-text'}`}>{widget.privacy === 'Private' ? <Sparkles className="h-3 w-3" /> : <UsersRound className="h-3 w-3" />}{widget.privacy}</span></div><div className="mt-3 flex items-center gap-2"><button type="button" className="flex flex-1 items-center justify-center gap-1.5 rounded-md border border-surface-200 py-2 text-[10px] font-bold text-navy-900 hover:border-mint-300 hover:bg-mint-50"><Edit3 className="h-3 w-3" /> {t('common.edit')}</button><button type="button" onClick={onAdd} className="flex flex-1 items-center justify-center gap-1.5 rounded-md border border-surface-200 py-2 text-[10px] font-bold text-navy-900 hover:border-mint-300 hover:bg-mint-50"><Bookmark className="h-3 w-3" /> {added ? t('home.addedToHome') : t('home.addToHome')}</button><button type="button" onClick={onMenu} className="flex h-8 w-8 items-center justify-center rounded-md border border-surface-200 text-navy-900 hover:bg-surface-50" aria-label={t('widgets.openMenu')}><Ellipsis className="h-4 w-4" /></button></div>{menuOpen && <WidgetMenu onShare={onShare} onPublish={onPublish} onEdit={onEdit} onRemove={onRemove} />}</article>;
}
function WidgetMenu({ onShare, onPublish, onEdit, onRemove }: { onShare: () => void; onPublish: () => void; onEdit: () => void; onRemove: () => void }) {
  const t = useT();
  const items: Array<[string, (() => void) | undefined]> = [
    [t('common.share'), onShare],
    [t('widgets.publishToCatalogue'), onPublish],
    [t('common.duplicate'), undefined],
  ];
  return <div className="absolute right-3 top-11 z-20 w-48 overflow-hidden rounded-lg border border-surface-200 bg-white py-1 shadow-floaty" onClick={(event) => event.stopPropagation()}>{items.map(([label, handler]) => <button type="button" key={label} onClick={handler} className="flex w-full items-center gap-2 px-3 py-2 text-left text-[11px] font-semibold text-ink-700 hover:bg-mint-50"><Edit3 className="h-3.5 w-3.5" />{label}</button>)}<div className="my-1 h-px bg-surface-100" /><button type="button" className="flex w-full items-center gap-2 px-3 py-2 text-left text-[11px] font-semibold text-red-600 hover:bg-red-50"><Trash2 className="h-3.5 w-3.5" />{t('common.delete')}</button></div>;
}
function WidgetReadOnlyView({ widget, onClose, onEdit }: { widget: Widget; onClose: () => void; onEdit: () => void }) {
  const t = useT();
  return <div className="fixed inset-0 z-50 flex items-center justify-center bg-overlay-light p-4"><section role="dialog" aria-modal="true" aria-labelledby="widget-view-title" className="relative w-full max-w-5xl rounded-lg border border-surface-200 bg-white p-6 shadow-floaty"><div className="flex items-start justify-between"><div><span className={`rounded-md px-2 py-1 text-[9px] font-bold tracking-wide ${kindStyles[widget.kind]}`}>{widget.kind}</span><h2 id="widget-view-title" className="mt-3 font-display text-[24px] font-bold text-navy-900">{widget.title}</h2><p className="mt-1 text-[14px] text-ink-500">{widget.description}</p></div><div className="flex items-center gap-2"><button type="button" onClick={onEdit} className="inline-flex items-center gap-2 rounded-lg border border-surface-200 px-3 py-2 text-[12px] font-bold text-navy-900 hover:bg-mint-50"><Edit3 className="h-4 w-4" /> {t('home.editWidget')}</button><button type="button" onClick={onClose} className="flex h-9 w-9 items-center justify-center rounded-lg text-ink-500 hover:bg-surface-100" aria-label={t('widgets.closeView')}><X className="h-5 w-5" /></button></div></div><div className="mt-8 min-h-[360px] rounded-lg border border-surface-200 bg-surface-50 p-6"><Preview widget={widget} /></div><div className="mt-4 flex items-center justify-between text-[12px] text-ink-500"><span>{widget.owner} · {widget.updated}</span><span className="font-semibold text-mint-700">{t('common.readOnlyView')}</span></div></section></div>;
}

function ShareWidgetModal({ widget, onClose }: { widget: Widget; onClose: () => void }) {
  const t = useT();
  const [search, setSearch] = useState('');
  const [recipients, setRecipients] = useState([t('widgets.retailLendingTeam'), t('widgets.amitSharma')]);
  const [message, setMessage] = useState('');
  const [notify, setNotify] = useState(true);
  const allSuggestions = [t('widgets.retailLendingTeam'), t('widgets.amitSharma'), t('widgets.riskComplianceTeam'), t('widgets.anitaGupta')];
  const suggestions = allSuggestions.filter((item) => item.toLowerCase().includes(search.toLowerCase()) && !recipients.includes(item));
  return <div className="fixed inset-0 z-50 flex items-center justify-center bg-overlay-medium p-4" role="presentation" onMouseDown={(event) => { if (event.target === event.currentTarget) onClose(); }}>
    <section role="dialog" aria-modal="true" aria-labelledby="share-widget-title" className="max-h-[calc(100vh-2rem)] w-full max-w-2xl overflow-y-auto rounded-lg border border-surface-200 bg-white p-6 shadow-floaty">
      <div className="flex items-start justify-between gap-4"><div><h2 id="share-widget-title" className="font-display text-[22px] font-bold text-navy-900">{t('widgets.shareWidget')}</h2><p className="mt-1 text-[16px] text-ink-500">{widget.title}</p></div><button type="button" onClick={onClose} className="text-[24px] leading-none text-ink-500 hover:text-navy-900" aria-label={t('common.close')} aria-hidden>×</button></div>
      <div className="mt-7"><h3 className="text-[15px] font-bold text-navy-900">{t('widgets.shareWith')}</h3><p className="mt-1 text-[13px] text-ink-500">{t('widgets.shareDesc')}</p><div className="mt-3 flex items-center gap-2 rounded-lg border border-surface-200 px-3 py-3"><Search className="h-4 w-4 text-ink-400" /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder={t('widgets.searchPeople')} className="min-w-0 flex-1 text-[13px] text-navy-900 outline-none placeholder:text-ink-400" /></div>{search && suggestions.length > 0 && <div className="mt-1 rounded-lg border border-surface-200 bg-white p-1 shadow-floaty">{suggestions.map((item) => <button type="button" key={item} onClick={() => { setRecipients((current) => [...current, item]); setSearch(''); }} className="block w-full rounded-md px-3 py-2 text-left text-[12px] font-semibold text-navy-900 hover:bg-mint-50">{item}<span className="ml-2 text-ink-400">{item.includes('Team') ? t('widgets.team') : t('widgets.person')}</span></button>)}</div>}<div className="mt-3 flex flex-wrap gap-2">{recipients.map((recipient) => <span key={recipient} className="inline-flex items-center gap-2 rounded-md border border-surface-200 bg-surface-50 px-3 py-2 text-[12px] font-semibold text-navy-900">{recipient}<button type="button" onClick={() => setRecipients((current) => current.filter((item) => item !== recipient))} className="text-[16px] leading-none text-ink-400 hover:text-navy-900" aria-label={t('widgets.removeRecipient', { name: recipient })} aria-hidden>×</button></span>)}</div></div>
      <div className="mt-6"><h3 className="text-[15px] font-bold text-navy-900">{t('widgets.permission')}</h3><p className="mt-1 text-[13px] text-ink-500">{t('widgets.permissionDesc')}</p><label className="mt-3 flex items-start gap-3"><input type="radio" name="permission" defaultChecked className="mt-1 accent-chart-green" /><span><span className="block text-[13px] font-bold text-navy-900">{t('widgets.canUseAdd')}</span><span className="block text-[12px] text-ink-500">{t('widgets.canUseDesc')}</span></span></label></div>
      <label className="mt-6 block text-[15px] font-bold text-navy-900">{t('widgets.message')} <span className="font-normal text-ink-500">{t('common.optional')}</span><textarea value={message} onChange={(event) => setMessage(event.target.value.slice(0, 200))} placeholder={t('widgets.addMessage')} className="mt-2 h-24 w-full resize-none rounded-lg border border-surface-200 px-3 py-3 text-[13px] font-normal text-navy-900 outline-none placeholder:text-ink-400 focus:border-mint-500" /><span className="block text-right text-[11px] font-normal text-ink-400">{t('widgets.charsCount', { count: String(message.length) })}</span></label>
      <div className="mt-4 flex items-center justify-between"><div><h3 className="text-[14px] font-bold text-navy-900">{t('widgets.notifyEmail')}</h3><p className="mt-1 text-[12px] text-ink-500">{t('widgets.notifyDesc')}</p></div><button type="button" onClick={() => setNotify((value) => !value)} aria-pressed={notify} className={`relative h-6 w-11 rounded-full transition ${notify ? 'bg-mint-500' : 'bg-surface-300'}`}><span className={`absolute top-1 h-4 w-4 rounded-full bg-white transition ${notify ? 'left-6' : 'left-1'}`} /></button></div>
      <div className="mt-6 flex items-center justify-between"><p className="text-[11px] text-ink-500">{t('widgets.recipientsSummary', { count: String(recipients.length) })}</p><div className="flex gap-2"><button type="button" onClick={onClose} className="rounded-lg border border-surface-200 px-4 py-2.5 text-[12px] font-bold text-navy-900 hover:bg-surface-50">{t('common.cancel')}</button><button type="button" disabled={!recipients.length} onClick={onClose} className="rounded-lg bg-mint-500 px-5 py-2.5 text-[12px] font-bold text-white hover:bg-mint-600 disabled:opacity-40">{t('common.share')}</button></div></div>
    </section>
  </div>;
}

function ShareToCatalogueModal({ widget, onClose }: { widget: Widget; onClose: () => void }) {
  const t = useT();
  const [category, setCategory] = useState(t('widgets.lending'));
  const [description, setDescription] = useState(widget.description);
  const [permission, setPermission] = useState<'view' | 'use'>('view');
  const cats = [t('widgets.lending'), t('widgets.risk'), t('widgets.collections'), t('widgets.sales'), t('widgets.operations')];
  return <div className="fixed inset-0 z-50 flex items-center justify-center bg-overlay-medium p-4" role="presentation" onMouseDown={(event) => { if (event.target === event.currentTarget) onClose(); }}>
    <section role="dialog" aria-modal="true" aria-labelledby="catalogue-title" className="max-h-[calc(100vh-2rem)] w-full max-w-2xl overflow-y-auto rounded-lg border border-surface-200 bg-white p-6 shadow-floaty">
      <div className="flex items-start justify-between gap-4"><div><h2 id="catalogue-title" className="font-display text-[22px] font-bold text-navy-900">{t('widgets.shareToCatalogue')}</h2><p className="mt-1 text-[14px] text-ink-500">{t('widgets.catalogueSubtitle')}</p></div><button type="button" onClick={onClose} className="text-[24px] leading-none text-ink-500 hover:text-navy-900" aria-label={t('common.close')} aria-hidden>×</button></div>
      <div className="mt-6"><h3 className="text-[14px] font-bold text-navy-900">{t('widgets.widget')}</h3><div className="mt-2 flex items-center gap-3 rounded-lg border border-surface-200 bg-surface-50 p-3"><span className={`flex h-10 w-10 items-center justify-center rounded-md ${kindStyles[widget.kind]}`}>{widget.kind === 'TABLE' ? <Grid2X2 className="h-5 w-5" /> : widget.kind === 'CHART' ? <BarChart3 className="h-5 w-5" /> : <Sparkles className="h-5 w-5" />}</span><div><div className="text-[14px] font-bold text-navy-900">{widget.title}</div><div className="mt-1 text-[12px] text-ink-500">{widget.kind[0] + widget.kind.slice(1).toLowerCase()} · {widget.updated}</div></div></div></div>
      <label className="mt-5 block text-[14px] font-bold text-navy-900">{t('common.category')}<select value={category} onChange={(event) => setCategory(event.target.value)} className="mt-2 w-full rounded-lg border border-surface-200 bg-white px-3 py-3 text-[13px] font-semibold text-navy-900 outline-none focus:border-mint-500">{cats.map((item) => <option key={item}>{item}</option>)}</select><span className="mt-1 block text-[11px] font-normal text-ink-500">{t('widgets.categoryHelp')}</span></label>
      <label className="mt-5 block text-[14px] font-bold text-navy-900">{t('widgets.description')} <span className="font-normal text-ink-500">{t('common.optional')}</span><textarea value={description} onChange={(event) => setDescription(event.target.value.slice(0, 200))} className="mt-2 h-24 w-full resize-none rounded-lg border border-surface-200 px-3 py-3 text-[13px] font-normal text-navy-900 outline-none focus:border-mint-500" /><span className="block text-right text-[11px] font-normal text-ink-400">{t('widgets.charsCount', { count: String(description.length) })}</span><span className="mt-1 block text-[11px] font-normal text-ink-500">{t('widgets.descriptionHelp')}</span></label>
      <fieldset className="mt-5"><legend className="text-[14px] font-bold text-navy-900">{t('widgets.permissions')}</legend><label className="mt-3 flex cursor-pointer items-start gap-3"><input type="radio" name="catalogue-permission" checked={permission === 'view'} onChange={() => setPermission('view')} className="mt-1 accent-chart-green" /><span><span className="block text-[13px] font-bold text-navy-900">{t('widgets.canView')}</span><span className="block text-[12px] text-ink-500">{t('widgets.canViewDesc')}</span></span></label><label className="mt-3 flex cursor-pointer items-start gap-3"><input type="radio" name="catalogue-permission" checked={permission === 'use'} onChange={() => setPermission('use')} className="mt-1 accent-chart-green" /><span><span className="block text-[13px] font-bold text-navy-900">{t('widgets.canUseAdd')}</span><span className="block text-[12px] text-ink-500">{t('widgets.canUseOrgDesc')}</span></span></label></fieldset>
      <div className="mt-5"><h3 className="text-[14px] font-bold text-navy-900">{t('common.preview')}</h3><div className="mt-2 max-w-[420px] rounded-lg border border-surface-200 p-2"><Preview widget={widget} /></div></div>
      <div className="mt-5 flex items-center gap-2 rounded-lg border border-blue-100 bg-blue-50 px-3 py-3 text-[12px] text-blue-800"><span className="flex h-5 w-5 items-center justify-center rounded-full border border-blue-500 font-bold">i</span>{t('widgets.publishedInfo')}</div>
      <div className="mt-5 flex justify-end gap-2"><button type="button" onClick={onClose} className="rounded-lg border border-surface-200 px-4 py-2.5 text-[12px] font-bold text-navy-900 hover:bg-surface-50">{t('common.cancel')}</button><button type="button" onClick={onClose} className="rounded-lg bg-mint-500 px-5 py-2.5 text-[12px] font-bold text-white hover:bg-mint-600">{t('widgets.publishButton')}</button></div>
    </section>
  </div>;
}

function Preview({ widget }: { widget: Widget }) {
  const t = useT();
  if (widget.preview === 'table') return <div className="mt-3 overflow-hidden rounded-md border border-surface-100 text-[8px]"><div className="grid grid-cols-2 bg-surface-50 px-2 py-1 font-bold text-ink-500"><span>{t('common.product')}</span><span className="text-right">{t('common.approvalRate')}</span></div>{[t('common.personalLoan'), t('common.homeLoan'), t('common.vehicleLoan'), t('common.businessLoan')].map((row, index) => <div key={row} className="grid grid-cols-2 border-t border-surface-100 px-2 py-1 text-ink-700"><span>{row}</span><span className="text-right">{['83.6%', '76.4%', '72.1%', '68.3%'][index]}</span></div>)}</div>;
  if (widget.preview === 'donut') return <div className="mt-3 flex h-[74px] items-center justify-center gap-3"><div className="donut-chart violet" /><div className="text-[8px] leading-4 text-ink-500">{t('common.north42')}<br />{t('common.west28')}<br />{t('common.south19')}</div></div>;
  if (widget.preview === 'bars') return <div className="mt-3 flex h-[74px] items-end gap-2 border-b border-surface-200 px-3">{[42, 60, 48, 76, 66, 71].map((height) => <span key={height} className="flex-1 rounded-t-sm bg-chart-blue-medium" style={{ height: `${height}%` }} />)}</div>;
  return <div className="mt-3 h-[74px]"><MiniLine large /></div>;
}
function MiniLine({ large = false }: { large?: boolean }) { return <svg className={large ? 'h-[74px] w-full' : 'h-12 w-20'} viewBox="0 0 120 50" fill="none" aria-hidden="true"><path d="M2 43C15 39 17 34 28 35C38 36 40 28 51 29C63 30 65 18 75 22C85 26 89 15 99 18C106 20 111 10 118 5V50H2Z" fill="var(--color-chart-green-fill)" /><path d="M2 43C15 39 17 34 28 35C38 36 40 28 51 29C63 30 65 18 75 22C85 26 89 15 99 18C106 20 111 10 118 5" stroke="var(--color-chart-green-stroke)" strokeWidth="2" /></svg>; }
