import { useMemo, useState, type ReactNode } from 'react';
import { BarChart3, Bookmark, Check, ChevronDown, Edit3, Ellipsis, Grid2X2, LayoutList, MoreHorizontal, Plus, Search, Share2, SlidersHorizontal, Sparkles, Trash2, UsersRound } from 'lucide-react';
import { myWidgets, recommendedWidgets, type Widget, type WidgetKind } from '@/data/homeData';

type Props = { onBack: () => void };
type Category = 'All' | 'Lending' | 'Risk' | 'Collections' | 'Sales' | 'Operations';
const categories: Category[] = ['All', 'Lending', 'Risk', 'Collections', 'Sales', 'Operations'];
const catalogueWidgets: Widget[] = [
  { id: 'catalogue-approval', kind: 'TABLE', title: 'Approval rate by product', description: 'Approval rate (%) by product and customer segment.', owner: 'You', initials: 'RA', updated: 'Updated 2h ago', privacy: 'Catalogue', preview: 'table', accent: 'mint' },
  { id: 'catalogue-npa', kind: 'CHART', title: 'NPA trend over time', description: 'Gross NPA (%) trend over the last 12 months.', owner: 'Anita Gupta', initials: 'AG', updated: 'Updated 1d ago', privacy: 'Catalogue', preview: 'line', accent: 'blue' },
  { id: 'catalogue-disbursed', kind: 'KPI', title: 'Total disbursed amount', description: 'Total loan amount disbursed this month.', owner: 'Rohit Mehta', initials: 'RM', updated: 'Updated 3d ago', privacy: 'Catalogue', value: '₹ 1,245 Cr', change: '12.4% vs last month', changeDirection: 'up', preview: 'line', accent: 'mint' },
  { id: 'catalogue-collection', kind: 'CHART', title: 'Collection efficiency trend', description: 'Collection efficiency (%) trend over time.', owner: 'S. Banerjee', initials: 'SB', updated: 'Updated 5d ago', privacy: 'Catalogue', preview: 'bars', accent: 'violet' },
  { id: 'catalogue-overdue', kind: 'TABLE', title: 'Top overdue accounts', description: 'Top 20 overdue accounts by outstanding amount.', owner: 'You', initials: 'RA', updated: 'Updated 5d ago', privacy: 'Private', preview: 'table', accent: 'mint' },
  ...recommendedWidgets,
];
const kindStyles: Record<WidgetKind, string> = { TABLE: 'bg-mint-100 text-mint-700', CHART: 'bg-[#eeebff] text-[#5e55ce]', KPI: 'bg-[#dff8ef] text-[#08865f]' };

export function WidgetsPage({ onBack }: Props) {
  const [tab, setTab] = useState<'mine' | 'catalogue'>('mine');
  const [category, setCategory] = useState<Category>('All');
  const [query, setQuery] = useState('');
  const [sort, setSort] = useState('Recently updated');
  const [list, setList] = useState(false);
  const [menuId, setMenuId] = useState<string | null>(null);
  const [added, setAdded] = useState<string[]>([]);
  const source = tab === 'mine' ? myWidgets : catalogueWidgets;
  const widgets = useMemo(() => source.filter((widget) => `${widget.title} ${widget.description} ${widget.owner}`.toLowerCase().includes(query.toLowerCase())), [source, query]);

  function addToHome(id: string) { setAdded((current) => current.includes(id) ? current : [...current, id]); }

  return <main className="min-h-0 flex-1 overflow-y-auto bg-white" onClick={() => menuId && setMenuId(null)}>
    <div className="mx-auto max-w-[1480px] px-5 py-6 sm:px-8 lg:px-10">
      <header className="flex flex-col justify-between gap-4 sm:flex-row sm:items-start"><div><h1 className="font-display text-[25px] font-bold tracking-[-0.04em] text-navy-900">Widgets</h1><p className="mt-1 text-[13px] text-ink-500">Discover, manage and use your widgets</p></div><button type="button" className="inline-flex items-center gap-2 self-start rounded-lg bg-navy-900 px-4 py-2.5 text-[12px] font-bold text-white transition hover:bg-navy-800"><Plus className="h-4 w-4" /> New widget</button></header>
      <div className="mt-6 border-b border-surface-200"><div className="flex gap-6"><button type="button" onClick={() => setTab('mine')} className={`border-b-2 px-1 pb-3 text-[12px] font-bold transition ${tab === 'mine' ? 'border-mint-500 text-mint-700' : 'border-transparent text-ink-500 hover:text-navy-900'}`}>My Widgets</button><button type="button" onClick={() => setTab('catalogue')} className={`border-b-2 px-1 pb-3 text-[12px] font-bold transition ${tab === 'catalogue' ? 'border-mint-500 text-mint-700' : 'border-transparent text-ink-500 hover:text-navy-900'}`}>Widget Catalogue</button></div></div>
      <div className="mt-5 flex flex-wrap items-center gap-2.5"><label className="flex min-w-[260px] flex-1 items-center gap-2 rounded-lg border border-surface-200 px-3 py-2.5 text-ink-300"><Search className="h-4 w-4" /><span className="sr-only">Search widgets</span><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search widgets..." className="min-w-0 flex-1 bg-transparent text-[12px] text-navy-900 outline-none placeholder:text-ink-400" /></label><div className="flex flex-wrap items-center gap-2">{categories.map((item) => <button type="button" key={item} onClick={() => setCategory(item)} className={`rounded-full border px-3.5 py-2 text-[11px] font-bold transition ${category === item ? 'border-navy-900 bg-navy-900 text-white' : 'border-surface-200 bg-white text-ink-600 hover:border-mint-300 hover:bg-mint-50'}`}>{item}</button>)}<button type="button" className="flex h-9 w-9 items-center justify-center rounded-full border border-surface-200 text-navy-900 hover:bg-surface-50" aria-label="More filters"><MoreHorizontal className="h-4 w-4" /></button></div><label className="flex items-center gap-2 text-[11px] text-ink-500">Sort by:<select value={sort} onChange={(event) => setSort(event.target.value)} className="rounded-lg border border-surface-200 bg-white px-3 py-2 text-[11px] font-bold text-navy-900 outline-none"><option>Recently updated</option><option>Name A–Z</option><option>Type</option></select></label><div className="flex rounded-lg border border-surface-200 p-0.5"><button type="button" onClick={() => setList(false)} className={`flex h-8 w-9 items-center justify-center rounded-md ${!list ? 'bg-mint-50 text-mint-700' : 'text-ink-500'}`} aria-label="Grid view"><Grid2X2 className="h-4 w-4" /></button><button type="button" onClick={() => setList(true)} className={`flex h-8 w-9 items-center justify-center rounded-md ${list ? 'bg-mint-50 text-mint-700' : 'text-ink-500'}`} aria-label="List view"><LayoutList className="h-4 w-4" /></button></div></div>
      <div className={`mt-5 grid gap-4 ${list ? 'grid-cols-1' : 'sm:grid-cols-2 xl:grid-cols-4'}`}>{widgets.map((widget) => <WidgetCard key={widget.id} widget={widget} menuOpen={menuId === widget.id} onMenu={(event) => { event.stopPropagation(); setMenuId(menuId === widget.id ? null : widget.id); }} added={added.includes(widget.id)} onAdd={() => addToHome(widget.id)} />)}</div>
      {!widgets.length && <div className="mt-5 rounded-lg border border-dashed border-surface-200 px-6 py-16 text-center text-[13px] text-ink-500">No widgets match your search.</div>}
      <div className="flex items-center justify-center gap-4 py-7 text-[11px] text-ink-500">Showing {widgets.length} of 32 widgets <button type="button" className="rounded-lg border border-surface-200 px-4 py-2 font-bold text-navy-900 hover:bg-surface-50">Load more <ChevronDown className="ml-1 inline h-3.5 w-3.5" /></button></div>
    </div>
  </main>;
}

function WidgetCard({ widget, menuOpen, onMenu, onAdd, added }: { widget: Widget; menuOpen: boolean; onMenu: (event: React.MouseEvent) => void; onAdd: () => void; added: boolean }) { return <article className="group relative flex min-h-[300px] flex-col rounded-lg border border-surface-200 bg-white p-4 shadow-[0_2px_8px_rgba(14,42,59,0.03)] transition hover:-translate-y-0.5 hover:border-mint-300 hover:shadow-floaty"><div className="flex items-start justify-between gap-2"><span className={`rounded-md px-2 py-1 text-[9px] font-bold tracking-wide ${kindStyles[widget.kind]}`}>{widget.kind}</span><button type="button" onClick={onMenu} aria-label={`More options for ${widget.title}`} className="text-navy-900"><Ellipsis className="h-4 w-4" /></button></div><h2 className="mt-3 text-[14px] font-bold tracking-[-0.02em] text-navy-900">{widget.title}</h2><p className="mt-1 min-h-8 text-[11px] leading-4 text-ink-500">{widget.description}</p><Preview widget={widget} /><div className="mt-auto flex items-center justify-between gap-2 pt-3 text-[9px] text-ink-500"><span className="flex min-w-0 items-center gap-1.5"><span className="flex h-5 w-5 shrink-0 items-center justify-center rounded-full bg-surface-100 text-[8px] font-bold text-navy-900">{widget.initials}</span><span className="truncate">{widget.owner} · {widget.updated}</span></span><span className={`flex shrink-0 items-center gap-1 font-bold ${widget.privacy === 'Private' ? 'text-mint-700' : 'text-[#5e55ce]'}`}>{widget.privacy === 'Private' ? <Sparkles className="h-3 w-3" /> : <UsersRound className="h-3 w-3" />}{widget.privacy}</span></div><div className="mt-3 flex items-center gap-2"><button type="button" className="flex flex-1 items-center justify-center gap-1.5 rounded-md border border-surface-200 py-2 text-[10px] font-bold text-navy-900 hover:border-mint-300 hover:bg-mint-50"><Edit3 className="h-3 w-3" /> Open</button><button type="button" onClick={onAdd} className="flex flex-1 items-center justify-center gap-1.5 rounded-md border border-surface-200 py-2 text-[10px] font-bold text-navy-900 hover:border-mint-300 hover:bg-mint-50"><Bookmark className="h-3 w-3" /> {added ? 'Added' : 'Add to home'}</button><button type="button" onClick={onMenu} className="flex h-8 w-8 items-center justify-center rounded-md border border-surface-200 text-navy-900 hover:bg-surface-50" aria-label="Open widget menu"><Ellipsis className="h-4 w-4" /></button></div>{menuOpen && <WidgetMenu />}</article>; }
function WidgetMenu() { return <div className="absolute right-3 top-11 z-20 w-48 overflow-hidden rounded-lg border border-surface-200 bg-white py-1 shadow-floaty" onClick={(event) => event.stopPropagation()}>{['Rename', 'Edit', 'Duplicate', 'Share', 'Publish to catalogue', 'Move to folder'].map((item) => <button type="button" key={item} className="flex w-full items-center gap-2 px-3 py-2 text-left text-[11px] font-semibold text-ink-700 hover:bg-mint-50"><Edit3 className="h-3.5 w-3.5" />{item}</button>)}<div className="my-1 h-px bg-surface-100" /><button type="button" className="flex w-full items-center gap-2 px-3 py-2 text-left text-[11px] font-semibold text-red-600 hover:bg-red-50"><Trash2 className="h-3.5 w-3.5" />Delete</button></div>; }
function Preview({ widget }: { widget: Widget }) { if (widget.kind === 'KPI') return <div className="mt-3 flex items-end justify-between rounded-md bg-surface-50 px-3 py-3"><div><div className="font-display text-[24px] font-bold text-navy-900">{widget.value}</div><div className="mt-1 text-[9px] font-bold text-mint-700">↑ {widget.change || '8.7% vs last month'}</div></div><MiniLine /></div>; if (widget.preview === 'table') return <div className="mt-3 overflow-hidden rounded-md border border-surface-100 text-[8px]"><div className="grid grid-cols-2 bg-surface-50 px-2 py-1 font-bold text-ink-500"><span>Product</span><span className="text-right">Approval rate (%)</span></div>{['Personal Loan', 'Home Loan', 'Vehicle Loan', 'Business Loan'].map((row, index) => <div key={row} className="grid grid-cols-2 border-t border-surface-100 px-2 py-1 text-ink-700"><span>{row}</span><span className="text-right">{['83.6%', '76.4%', '72.1%', '68.3%'][index]}</span></div>)}</div>; if (widget.preview === 'donut') return <div className="mt-3 flex h-[74px] items-center justify-center gap-3"><div className="donut-chart violet" /><div className="text-[8px] leading-4 text-ink-500">North 42%<br />West 28%<br />South 19%</div></div>; if (widget.preview === 'bars') return <div className="mt-3 flex h-[74px] items-end gap-2 border-b border-surface-200 px-3">{[42, 60, 48, 76, 66, 71].map((height) => <span key={height} className="flex-1 rounded-t-sm bg-[#9589e9]" style={{ height: `${height}%` }} />)}</div>; return <div className="mt-3 h-[74px]"><MiniLine large /></div>; }
function MiniLine({ large = false }: { large?: boolean }) { return <svg className={large ? 'h-[74px] w-full' : 'h-12 w-20'} viewBox="0 0 120 50" fill="none" aria-hidden="true"><path d="M2 43C15 39 17 34 28 35C38 36 40 28 51 29C63 30 65 18 75 22C85 26 89 15 99 18C106 20 111 10 118 5V50H2Z" fill="#d8f7eb" /><path d="M2 43C15 39 17 34 28 35C38 36 40 28 51 29C63 30 65 18 75 22C85 26 89 15 99 18C106 20 111 10 118 5" stroke="#0caf78" strokeWidth="2" /></svg>; }
