api.host=localhost
api.port=8080
api.basePath=/api
api.homeWidgets.mode=mock
api.homeWidgets.path=/widgets/home
api.widgetData.mode=mock
api.widgetData.path=/widgets/{widgetId}/data
api.widgetData.approval.mode=mock
api.widgetData.approval.path=/widgets/{widgetId}/data
api.widgetData.branch-performance.mode=mock
api.widgetData.branch-performance.path=/widgets/{widgetId}/data
api.widgetData.npa-trend.mode=mock
api.widgetData.npa-trend.path=/widgets/{widgetId}/data
api.widgetData.loan-region.mode=mock
api.widgetData.loan-region.path=/widgets/{widgetId}/data
api.widgetMutations.mode=mock
api.widgetMutations.path=/widgets/{widgetId}/home
